-- ============================================================================
-- TEMPORARY UAT COMPATIBILITY SHIM — Zepto sales tables
--
-- Created 2026-08-31. DELETE THIS once dev/main carry the renamed models.
--
-- WHY
-- Migrations a3f7c92e51d8 and b6d24a08f3c1 renamed two Zepto tables and dropped
-- a third. Every branch shares one Supabase database, so the moment they ran,
-- code on dev/main that still says the old names started failing — which is why
-- Zepto shows no data on UAT.
--
--     zepto_seller_product_perf      -> renamed to zepto_seller_sales
--     zepto_seller_sales_daily       -> renamed to zepto_seller_sales_summary
--     zepto_seller_sales_city_daily  -> dropped (superseded by
--                                       zepto_seller_product_city_daily)
--
-- This restores the OLD names without moving data and without touching the new
-- ones, so UAT and feature/zepto-public-scrape both work at the same time.
--
-- NOT AN ALEMBIC MIGRATION, deliberately: it is scaffolding that must NOT
-- travel with the code. It is run by hand and removed by hand.
--
-- ── what each piece does ────────────────────────────────────────────────────
-- The two renamed tables get VIEWS. A view stores nothing; it forwards the old
-- name to the new table. Postgres makes a single-table view with no aggregates
-- auto-updatable, so UAT can INSERT and UPDATE through them as well as read.
--
-- The dropped table gets a REAL TABLE back, because dev's storage.py upserts
-- into it (storage.py:32) and cli/commands/scrape.py:1641 selects from it — a
-- view over the aggregated replacement would not be writable. Its definition is
-- copied from the downgrade() of a3f7c92e51d8.
--
-- ── data ────────────────────────────────────────────────────────────────────
-- Steps 1-3 move no rows. Step 4 is OPTIONAL and re-derives the 14 rows the
-- dropped table used to hold, so UAT shows history instead of waiting for the
-- next scrape. Every one of those rows was verified reproducible from
-- zepto_seller_product_city_daily before the drop.
--
-- ── to undo (run once UAT has pulled the renamed code) ──────────────────────
--     DROP VIEW  IF EXISTS zepto_seller_product_perf;
--     DROP VIEW  IF EXISTS zepto_seller_sales_daily;
--     DROP TABLE IF EXISTS zepto_seller_sales_city_daily;
-- ============================================================================

BEGIN;

-- ── 1. forward the per-SKU sales table ──────────────────────────────────────
CREATE VIEW zepto_seller_product_perf AS
    SELECT * FROM zepto_seller_sales;

-- ── 2. forward the daily brand-totals table ─────────────────────────────────
CREATE VIEW zepto_seller_sales_daily AS
    SELECT * FROM zepto_seller_sales_summary;

-- ── 3. put the dropped table back, empty ────────────────────────────────────
-- Column-for-column as it was: see a3f7c92e51d8 downgrade().
CREATE TABLE zepto_seller_sales_city_daily (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     uuid       NOT NULL REFERENCES tenants (id),
    platform      varchar    NOT NULL,
    upsert_key    varchar    NOT NULL UNIQUE,
    scrape_job_id uuid       NULL REFERENCES scrape_jobs (id),
    date          date       NOT NULL,
    brand_id      varchar    NOT NULL,
    city_id       varchar    NOT NULL,
    city_name     varchar    NULL,
    gmv           double precision NOT NULL,
    units         integer    NOT NULL,
    scraped_at    timestamp  NOT NULL
);

CREATE INDEX idx_zsscd_tenant_date
    ON zepto_seller_sales_city_daily (tenant_id, date);

COMMIT;


-- ============================================================================
-- 4. OPTIONAL BACKFILL — run separately, only if UAT should show history.
--
-- Re-derives brand GMV/units per city per day from the finer-grained table that
-- replaced it. Skip this and the table simply fills on the next Zepto scrape.
--
-- Writes ~14 rows for the tenant that had them. Safe to re-run: the upsert_key
-- is unique and ON CONFLICT DO NOTHING makes it idempotent.
-- ============================================================================

-- INSERT INTO zepto_seller_sales_city_daily
--     (tenant_id, platform, upsert_key, date, brand_id, city_id, city_name,
--      gmv, units, scraped_at)
-- SELECT tenant_id,
--        'zepto',
--        tenant_id || ':' || date || ':' || city_id,
--        date,
--        'brik-oven',
--        city_id,
--        max(city_name),
--        sum(gmv),
--        sum(qty_sold),
--        max(scraped_at)
-- FROM zepto_seller_product_city_daily
-- GROUP BY tenant_id, date, city_id
-- ON CONFLICT (upsert_key) DO NOTHING;
