"""initial schema

Revision ID: 627daf7d24e9
Revises: 
Create Date: 2026-06-16 17:06:56.003328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '627daf7d24e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_slug'), 'brands', ['slug'], unique=True)
    op.create_table('marketplaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplaces_slug'), 'marketplaces', ['slug'], unique=True)
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mp_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['brand_slug'], ['brands.slug'], ),
    sa.ForeignKeyConstraint(['mp_slug'], ['marketplaces.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitor_rankings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mp_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('zone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pincode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('competitor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['brand_slug'], ['brands.slug'], ),
    sa.ForeignKeyConstraint(['mp_slug'], ['marketplaces.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cr_brand', 'competitor_rankings', ['brand_slug', 'city', 'keyword'], unique=False)
    op.create_index('idx_cr_competitor', 'competitor_rankings', ['competitor', 'city', 'mp_slug'], unique=False)
    op.create_table('inventory_depth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mp_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('zone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pincode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('max_allowed', sa.Integer(), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('stock_msg', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('platform_product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['brand_slug'], ['brands.slug'], ),
    sa.ForeignKeyConstraint(['mp_slug'], ['marketplaces.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_brand_sku', 'inventory_depth', ['brand_slug', 'sku', 'mp_slug', 'city'], unique=False)
    op.create_index('idx_inv_time', 'inventory_depth', ['brand_slug', 'scraped_at'], unique=False)
    op.create_table('platform_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encrypted_session', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dashboard', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', name='jobstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('records_written', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_status', 'scrape_jobs', ['status'], unique=False)
    op.create_index('idx_jobs_tenant', 'scrape_jobs', ['tenant_id', 'platform'], unique=False)
    op.create_table('scraped_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mp_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['brand_slug'], ['brands.slug'], ),
    sa.ForeignKeyConstraint(['mp_slug'], ['marketplaces.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mp_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('zone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pincode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('merchant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('store_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('brand_rank', sa.Integer(), nullable=True),
    sa.Column('brand_sov', sa.Float(), nullable=True),
    sa.Column('total_results', sa.Integer(), nullable=True),
    sa.Column('products', sa.JSON(), nullable=True),
    sa.Column('competitors', sa.JSON(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['brand_slug'], ['brands.slug'], ),
    sa.ForeignKeyConstraint(['mp_slug'], ['marketplaces.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sr_brand_mp', 'search_results', ['brand_slug', 'mp_slug'], unique=False)
    op.create_index('idx_sr_city', 'search_results', ['brand_slug', 'city'], unique=False)
    op.create_index('idx_sr_keyword', 'search_results', ['brand_slug', 'keyword', 'city'], unique=False)
    op.create_index('idx_sr_scraped', 'search_results', ['scraped_at'], unique=False)
    op.create_index('idx_sr_zone', 'search_results', ['brand_slug', 'city', 'zone'], unique=False)
    op.create_table('tenant_watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('brand_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relationship', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cities', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('marketplaces', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_slug'], ['brands.slug'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_tenant', 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ad_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upsert_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_ts', sa.DateTime(), nullable=True),
    sa.Column('end_ts', sa.DateTime(), nullable=True),
    sa.Column('infinite_campaign', sa.Boolean(), nullable=False),
    sa.Column('budget_consumed', sa.Float(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('atcs', sa.Integer(), nullable=False),
    sa.Column('roas', sa.Float(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upsert_key')
    )
    op.create_index('idx_ac_tenant_date', 'ad_campaigns', ['tenant_id', 'date'], unique=False)
    op.create_table('ad_performance_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upsert_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('budget_consumed', sa.Float(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('budget_distribution', sa.JSON(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upsert_key')
    )
    op.create_table('blinkit_po_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upsert_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upsert_key')
    )
    op.create_table('blinkit_pos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upsert_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
    sa.Column('po_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upsert_key')
    )
    op.create_index('idx_pos_tenant_po', 'blinkit_pos', ['tenant_id', 'po_number'], unique=False)
    op.create_table('blinkit_scorecard_facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upsert_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('from_date_ist', sa.Date(), nullable=False),
    sa.Column('facility_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('facility_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_po_quantity', sa.Integer(), nullable=False),
    sa.Column('total_grn_quantity', sa.Integer(), nullable=False),
    sa.Column('fill_rate', sa.Float(), nullable=False),
    sa.Column('weighted_fill_rate_percent', sa.Float(), nullable=False),
    sa.Column('potential_loss', sa.Float(), nullable=False),
    sa.Column('manufacturer_rank', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upsert_key')
    )
    op.create_index('idx_scf_tenant', 'blinkit_scorecard_facilities', ['tenant_id', 'from_date_ist'], unique=False)
    op.create_table('blinkit_scorecard_key_skus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upsert_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('from_date_ist', sa.Date(), nullable=False),
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('upc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('variant_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('proxy_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('potential_loss', sa.Float(), nullable=False),
    sa.Column('total_gmv', sa.Float(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upsert_key')
    )
    op.create_index('idx_scs_tenant', 'blinkit_scorecard_key_skus', ['tenant_id', 'from_date_ist'], unique=False)
    op.create_table('blinkit_scorecard_weekly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upsert_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('from_date_ist', sa.Date(), nullable=False),
    sa.Column('overall', sa.JSON(), nullable=False),
    sa.Column('best_category', sa.JSON(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upsert_key')
    )
    op.create_index('idx_scw_tenant', 'blinkit_scorecard_weekly', ['tenant_id', 'from_date_ist'], unique=False)
    op.create_table('blinkit_seller_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upsert_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('qty_sold', sa.Integer(), nullable=False),
    sa.Column('mrp_value', sa.Float(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upsert_key')
    )
    op.create_index('idx_bss_tenant_date', 'blinkit_seller_sales', ['tenant_id', 'date'], unique=False)
    op.create_table('blinkit_seller_sales_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upsert_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('distinct_skus', sa.Integer(), nullable=False),
    sa.Column('distinct_categories', sa.Integer(), nullable=False),
    sa.Column('max_sell_item', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upsert_key')
    )
    op.create_table('blinkit_soh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upsert_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('backend_facility_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('backend_facility_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('manufacturer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('backend_inv_qty', sa.Integer(), nullable=False),
    sa.Column('frontend_inv_qty', sa.Integer(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upsert_key')
    )
    op.create_index('idx_soh_tenant_date', 'blinkit_soh', ['tenant_id', 'date'], unique=False)
    op.create_table('brand_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upsert_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('collection_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('number_of_products', sa.Integer(), nullable=False),
    sa.Column('is_dynamic', sa.Boolean(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_on', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upsert_key')
    )
    op.create_table('sponsored_sov',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upsert_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monthly_searches', sa.Integer(), nullable=False),
    sa.Column('searches', sa.Integer(), nullable=False),
    sa.Column('sov', sa.Float(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upsert_key')
    )
    op.create_index('idx_sov_tenant', 'sponsored_sov', ['tenant_id', 'date'], unique=False)
    op.create_table('visibility_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upsert_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upsert_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visibility_plans')
    op.drop_index('idx_sov_tenant', table_name='sponsored_sov')
    op.drop_table('sponsored_sov')
    op.drop_table('brand_collections')
    op.drop_index('idx_soh_tenant_date', table_name='blinkit_soh')
    op.drop_table('blinkit_soh')
    op.drop_table('blinkit_seller_sales_summary')
    op.drop_index('idx_bss_tenant_date', table_name='blinkit_seller_sales')
    op.drop_table('blinkit_seller_sales')
    op.drop_index('idx_scw_tenant', table_name='blinkit_scorecard_weekly')
    op.drop_table('blinkit_scorecard_weekly')
    op.drop_index('idx_scs_tenant', table_name='blinkit_scorecard_key_skus')
    op.drop_table('blinkit_scorecard_key_skus')
    op.drop_index('idx_scf_tenant', table_name='blinkit_scorecard_facilities')
    op.drop_table('blinkit_scorecard_facilities')
    op.drop_index('idx_pos_tenant_po', table_name='blinkit_pos')
    op.drop_table('blinkit_pos')
    op.drop_table('blinkit_po_snapshots')
    op.drop_table('ad_performance_summary')
    op.drop_index('idx_ac_tenant_date', table_name='ad_campaigns')
    op.drop_table('ad_campaigns')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_tenant', table_name='users')
    op.drop_table('users')
    op.drop_table('tenant_watchlist')
    op.drop_index('idx_sr_zone', table_name='search_results')
    op.drop_index('idx_sr_scraped', table_name='search_results')
    op.drop_index('idx_sr_keyword', table_name='search_results')
    op.drop_index('idx_sr_city', table_name='search_results')
    op.drop_index('idx_sr_brand_mp', table_name='search_results')
    op.drop_table('search_results')
    op.drop_table('scraped_products')
    op.drop_index('idx_jobs_tenant', table_name='scrape_jobs')
    op.drop_index('idx_jobs_status', table_name='scrape_jobs')
    op.drop_table('scrape_jobs')
    op.drop_table('platform_sessions')
    op.drop_index('idx_inv_time', table_name='inventory_depth')
    op.drop_index('idx_inv_brand_sku', table_name='inventory_depth')
    op.drop_table('inventory_depth')
    op.drop_index('idx_cr_competitor', table_name='competitor_rankings')
    op.drop_index('idx_cr_brand', table_name='competitor_rankings')
    op.drop_table('competitor_rankings')
    op.drop_table('brand_snapshots')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_marketplaces_slug'), table_name='marketplaces')
    op.drop_table('marketplaces')
    op.drop_index(op.f('ix_brands_slug'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
