"""uq_jobs_active: a bid RESET is not a bid OPTIMIZER run

Revision ID: a2d5f81c9b34
Revises: f4c81b3d7e26
Create Date: 2026-09-05

THE PROBLEM

Two opposite operations share one job type. `cm.bid_optimizer` RAISES bids every 15
minutes while a window is open; the same job type with `params={"reset": "true"}`
LOWERS them back to the floor, once, just before the window closes. The only thing
telling them apart is that flag.

`uq_jobs_active` keys on (job_type, tenant_id, marketplace), so the guard reads them
as the same job. If an optimizer run is still going when the reset falls due, the
reset is rejected as a duplicate — and the scheduler DROPS a rejected fire rather
than deferring it:

    except DuplicateActiveJob:
        log.warning(f"'{sched.name}': previous run still active — skipped")
        return None

No job row, so nothing appears in `cli status` or the deadman check. The window then
closes with bids still at the level the optimizer pushed them to, and they stay there
until the next window opens — overnight, at peak rates.

Measured 2026-09-05: optimizer runs take 87s-547s (that spread is browser setup, not
keyword count — there is currently ONE active bid rule). A tick at :45 finishing at
:54 clears a :59 reset by five minutes. A slower one does not. This has not bitten
yet; the margin is simply thinner than docs/campaign-manager.md claimed ("harmless at
~30 s runs").

WHY WIDENING THE KEY IS SAFE

The guard is right about optimizer-vs-optimizer: two concurrent runs would both write
bids AND both update `cm_bid_runtime` — the escalation memory (`last_step`, `at_max`,
`stored_target`) — so one would overwrite the other's feedback and the bid would climb
on corrupted state. That stays blocked.

It was never right about optimizer-vs-reset. The two act on DISJOINT keyword sets by
construction: the optimizer takes rules whose window is open, and `_reset_run` takes
rules whose window is closed, explicitly excluding any still covered by an in-window
rule. Different keywords, different `cm_bid_runtime` rows, nothing shared.

⚠️ Except at the boundary, and that is fixed in code alongside this migration, not
here: the reset looks `RESET_LOOKAHEAD_MINUTES` (2) ahead, so for ~2 minutes at window
close the optimizer still sees a keyword as open while the reset sees it closed. Once
they may run together, that sliver becomes a real race over one bid. `bid.py` now has
the optimizer skip any keyword within that look-ahead of closing — it is about to be
reset anyway, so raising its bid there was always wasted money.

THE CHANGE

    before: UNIQUE (job_type, tenant_id, COALESCE(params->>'marketplace','blinkit'))
    after:  ... + COALESCE(params->>'reset', 'false')
    both:   WHERE status IN ('pending','running')

⚠️ The COALESCE is load-bearing, for the same reason it was on `marketplace`: a bare
`params->>'reset'` is NULL on every job that is not a reset, and NULLs are DISTINCT in
a unique index — which would silently disable the overlap guard for exactly the jobs
that rely on it. Verified: `json_object_field_text` is IMMUTABLE, so the expression is
indexable.

SAFETY

Adding a column to a unique index only ever permits MORE rows, so no existing data can
violate it. Safe to apply ahead of the deploy: running code does not name the new
expression, and the new index accepts everything the old one did. The dangerous
ordering is the reverse — code before migration.

Hand-written, NOT autogenerated (an expression index cannot be autogenerated).
"""
from typing import Sequence, Union

from alembic import op

revision: str = "a2d5f81c9b34"
down_revision: Union[str, Sequence[str], None] = "f4c81b3d7e26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Mirrors the predicate already on the index, enum casts included.
_ACTIVE = "status = ANY (ARRAY['pending'::jobstatus, 'running'::jobstatus])"
_MP = "COALESCE(params->>'marketplace', 'blinkit')"
_RESET = "COALESCE(params->>'reset', 'false')"


def upgrade() -> None:
    op.drop_index("uq_jobs_active", table_name="jobs")
    op.execute(
        f"CREATE UNIQUE INDEX uq_jobs_active ON jobs "
        f"(job_type, tenant_id, {_MP}, {_RESET}) WHERE {_ACTIVE}"
    )


def downgrade() -> None:
    # ⚠️ NARROWING a unique index can fail on live data: if an optimizer run and a
    # reset for the same tenant are both active at that moment, they collide under the
    # old key. Retry when the lane is idle — that pair is exactly what this migration
    # made possible.
    op.drop_index("uq_jobs_active", table_name="jobs")
    op.execute(
        f"CREATE UNIQUE INDEX uq_jobs_active ON jobs "
        f"(job_type, tenant_id, {_MP}) WHERE {_ACTIVE}"
    )
