"""zepto: drop the orphaned sales_city_daily table

Revision ID: a3f7c92e51d8
Revises: c1e8a4d20f7b
Create Date: 2026-08-30

HAND-WRITTEN, not autogenerated — following the note on c8f4e91a37d2.

────────────────────────────────────────────────────────────────────────────────
WHY

`zepto_seller_sales_city_daily` holds brand GMV/units per city per day. It was
superseded by `zepto_seller_product_city_daily`, which holds the same money at a
FINER grain (per SKU as well as per city) and is what the Analytics heatmap
actually reads.

The model class and every code path were removed in 4a2e97d ("Zepto: drop the
redundant sales_city_daily table"), but no migration ever dropped the table. So
it has been sitting in Supabase since then with 14 rows, no model, and nothing
reading it. This finishes that commit.

────────────────────────────────────────────────────────────────────────────────
PROOF THAT NOTHING IS LOST

Every one of the 14 rows was checked individually against
`zepto_seller_product_city_daily`, aggregated to (date, city):

    date         city               sales_city_daily   product_city_daily
    2026-08-14   BLR - Bengaluru             65,040    65,040   match
    2026-08-15   BLR - Bengaluru             40,590    40,590   match
    2026-08-16   BLR - Bengaluru             58,960    58,960   match
    2026-08-17   BLR - Bengaluru             47,500    47,500   match
    2026-08-18   BLR - Bengaluru             66,145    66,145   match
    2026-08-19   BLR - Bengaluru             72,105    72,105   match
    2026-08-20   BLR - Bengaluru             45,070    45,070   match
    2026-08-21   BLR - Bengaluru             65,730    65,730   match
    2026-08-21   HOS - Hosur                    220       220   match
    2026-08-22   BLR - Bengaluru             66,965    66,965   match
    2026-08-23   BLR - Bengaluru             81,545    81,545   match
    2026-08-24   BLR - Bengaluru             32,880    32,880   match
    2026-08-25   BLR - Bengaluru             52,215    52,215   match
    2026-08-26   BLR - Bengaluru             59,810    59,810   match

    14 of 14 covered, 0 differ, 0 missing.

Both tables span the same range (2026-08-14 .. 2026-08-26) and the same two
cities. The Hosur row — the one genuinely interesting record, a city that sells
two units and reports no stock — survives in `product_city_daily`, and the
finding it produced is written up in docs/zepto.md.

────────────────────────────────────────────────────────────────────────────────
CODE IMPACT

None. Verified by grep across the repo: the only remaining mention of
`zepto_seller_sales_city_daily` is a comparative comment in
`app/services/zepto_analytics.py`, explaining why the per-SKU city table is used
instead. No import, no query, no model.

────────────────────────────────────────────────────────────────────────────────
DISK

`DROP TABLE` genuinely reclaims space, unlike `DELETE` which only marks rows
dead. Frees ~64 kB. Small, but the project runs against a 500 MB Supabase cap.

────────────────────────────────────────────────────────────────────────────────
DOWNGRADE

Recreates the table with its original structure, keys and index — but NOT its
rows. That is the honest behaviour: the data is recoverable by re-deriving it
from `zepto_seller_product_city_daily`, not by running a downgrade. If you need
the rows back:

    INSERT INTO zepto_seller_sales_city_daily
        (tenant_id, platform, upsert_key, date, brand_id, city_id, city_name,
         gmv, units, scraped_at)
    SELECT tenant_id, 'zepto',
           tenant_id || ':' || date || ':' || city_id,
           date, 'brik-oven', city_id, max(city_name),
           sum(gmv), sum(qty_sold), max(scraped_at)
    FROM zepto_seller_product_city_daily
    GROUP BY tenant_id, date, city_id;
"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

revision = "a3f7c92e51d8"
down_revision = "c1e8a4d20f7b"
branch_labels = None
depends_on = None

_STR = sqlmodel.sql.sqltypes.AutoString


def upgrade() -> None:
    op.drop_index(
        "idx_zsscd_tenant_date", table_name="zepto_seller_sales_city_daily"
    )
    op.drop_table("zepto_seller_sales_city_daily")


def downgrade() -> None:
    op.create_table(
        "zepto_seller_sales_city_daily",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("platform", _STR(), nullable=False),
        sa.Column("upsert_key", _STR(), nullable=False),
        sa.Column("scrape_job_id", sa.Uuid(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("brand_id", _STR(), nullable=False),
        sa.Column("city_id", _STR(), nullable=False),
        sa.Column("city_name", _STR(), nullable=True),
        sa.Column("gmv", sa.Float(), nullable=False),
        sa.Column("units", sa.Integer(), nullable=False),
        sa.Column("scraped_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["scrape_job_id"], ["scrape_jobs.id"]),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("upsert_key"),
    )
    op.create_index(
        "idx_zsscd_tenant_date",
        "zepto_seller_sales_city_daily",
        ["tenant_id", "date"],
    )
