"""cm_run_log.rule_id is TEXT — a bid rule's id is a uuid hex string, not an int

Revision ID: a4e7c2f19b83
Revises: a2d5f81c9b34
Create Date: 2026-09-07

`f4c81b3d7e26` added `rule_id` as INTEGER. The only writer of that column is the bid
engine, and a bid rule's primary key is a **uuid hex string** (`cm_bid_rules.id`) — so
every tick that carried a rule_id died on the INSERT:

    asyncpg.exceptions.DataError: invalid input for query argument $9:
    'd657c360345f421d866bcde09a702e42' ('str' object cannot be interpreted as an integer)

Two consequences, both bad, and both live from 2026-09-04 until this migration:

1. **The history write happens AFTER the bids are written to Blinkit.** The marketplace
   was updated, then the run blew up and exited 1 — real writes with no record of them,
   and a scheduled job that alerts as failed every tick.
2. **The runaway-write guard reads this table.** `repo.recent_write_count` counts
   `cm_run_log` rows with `dry_run = false`; with no rows landing it counts zero, so the
   cap that is supposed to stop a bid loop was silently not counting anything.

TEXT rather than a second int column, because the id genuinely is a string; a budget
rule's int id, if it is ever logged here, is stored as its string form. Still not a
foreign key — history must outlive the rule it describes (see `f4c81b3d7e26`).

**No data is converted.** Every row that would have carried a rule_id failed to insert,
so the column is 100% NULL; the `USING` cast is there for correctness, not for rows.

Hand-written, NOT autogenerated.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'a4e7c2f19b83'
down_revision: Union[str, Sequence[str], None] = 'a2d5f81c9b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column('cm_run_log', 'rule_id',
                    existing_type=sa.Integer(), type_=sa.String(),
                    existing_nullable=True,
                    postgresql_using='rule_id::varchar')


def downgrade() -> None:
    # Only reversible while the column holds nothing but NULLs and digit strings — which is
    # the state this migration found it in. A uuid hex id cannot be cast back to an integer.
    op.alter_column('cm_run_log', 'rule_id',
                    existing_type=sa.String(), type_=sa.Integer(),
                    existing_nullable=True,
                    postgresql_using='rule_id::integer')
