"""zepto campaign catalogue — current-state campaigns + their keywords (ZC-B2/B3)

Revision ID: a6d2f9c41e87
Revises: f3c8a1d6b9e2
Create Date: 2026-09-21

Zepto's equivalents of `blinkit_ad_campaigns` / `blinkit_ad_campaign_keywords`: what every
campaign is configured to do RIGHT NOW, which the campaign manager needs for Zepto and
which no existing Zepto table holds (`zepto_ad_campaign_daily` is metrics, and
`zepto_ad_keyword_daily` has no campaign id at all).

1. **`zepto_ad_campaigns`** — one row per (tenant, campaign), upserted in place: identity,
   current status, type/sub-type/bid-targeting, budgets, dates, and — for PLA campaigns,
   from the per-campaign detail — city mode + chosen cities (JSON), store targeting, the
   advertised product ids (JSON) and `detail_scraped_at`.

2. **`zepto_ad_campaign_keywords`** — one row per (tenant, campaign, keyword, match_type):
   negative flag, live bid, Zepto's published minimum bid. A campaign's rows are replaced
   whole each time its detail is read.

Filled by the daily Zepto ads scrape (like Blinkit's marketing scrape fills its catalogue)
and refreshed between scrapes by `cm.sync_campaigns -m zepto` (list fields only).

No existing table changes and no backfill — the first scrape after deploy fills them.
Additive only: code that predates this never touches either table. Apply BEFORE deploying
code whose models declare them.

`downgrade` drops both tables and everything in them (rebuildable from one scrape).

Hand-written, NOT autogenerated.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

revision: str = 'a6d2f9c41e87'
down_revision: Union[str, Sequence[str], None] = 'f3c8a1d6b9e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'zepto_ad_campaigns',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('upsert_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
        sa.Column('campaign_id', sa.Integer(), nullable=False),
        sa.Column('campaign_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('brand_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('campaign_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('campaign_sub_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('bid_targeting_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('daily_budget', sa.Integer(), nullable=True),
        sa.Column('lifetime_budget', sa.Integer(), nullable=True),
        sa.Column('campaign_start_date', sa.DateTime(), nullable=True),
        sa.Column('campaign_end_date', sa.DateTime(), nullable=True),
        sa.Column('city_targeting', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('cities', sa.JSON(), nullable=True),
        sa.Column('store_targeting', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('product_variant_ids', sa.JSON(), nullable=True),
        sa.Column('detail_scraped_at', sa.DateTime(), nullable=True),
        sa.Column('scraped_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('upsert_key'),
    )
    op.create_index('idx_zac_tenant', 'zepto_ad_campaigns', ['tenant_id'])

    op.create_table(
        'zepto_ad_campaign_keywords',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('upsert_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
        sa.Column('campaign_id', sa.Integer(), nullable=False),
        sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('match_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_negative', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('bid_value', sa.Integer(), nullable=True),
        sa.Column('min_bid', sa.Integer(), nullable=True),
        sa.Column('scraped_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('upsert_key'),
    )
    op.create_index('idx_zackw_tenant_campaign', 'zepto_ad_campaign_keywords',
                    ['tenant_id', 'campaign_id'])


def downgrade() -> None:
    op.drop_index('idx_zackw_tenant_campaign', table_name='zepto_ad_campaign_keywords')
    op.drop_table('zepto_ad_campaign_keywords')
    op.drop_index('idx_zac_tenant', table_name='zepto_ad_campaigns')
    op.drop_table('zepto_ad_campaigns')
