"""blinkit: keyword performance per day + a daily budget on each day (BLINKIT-NOTES B6, B8)

Revision ID: a6d3f9b2c8e1
Revises: e7b2c9d4a6f3
Create Date: 2026-10-08

ONE new table and ONE new nullable column:

**`blinkit_ad_campaign_detail_daily`** — the per-campaign keyword / recommendation report,
one row per sub-campaign target per DAY. The existing `blinkit_ad_campaign_detail` holds an
8-day total (today − 7 … today) under each scrape day, so its rows overlap and no date window
can be read from them (Ads Insights labels them as a snapshot). Probed read-only 2026-10-08
(campaign 402379): the report answers a one-day range, single days add up, and past days still
answer — so the scrape asks each campaign × day it spent on. Zepto's `zepto_ad_campaign_detail`
pattern.

**`blinkit_ad_campaign_daily.daily_budget`** (nullable int) — the campaign's budget ON that day.
Blinkit keeps no budget history and `blinkit_ad_campaigns.daily_budget` is overwritten every
scrape, so utilisation for a past day used today's budget. The morning scrape writes the
budget it reads onto yesterday's row and never replaces it on a re-scrape — the way Zepto's
`zepto_ad_campaign_daily.daily_budget` works. NULL for days before it ships.

Additive only: code that predates this never touches the new table, and its daily-row upsert
names its own columns, so it neither writes nor clears the new column. The old detail
snapshot keeps being written (and read by older code) until it is retired after deploy.
Apply BEFORE running or deploying code whose models declare these — that code writes them on
every marketing scrape and would fail the save without them.

Names checked free in `pg_class` on 2026-10-08 (index names are database-wide: "bacd" and
"bacdet" are taken, hence "bacdd").

`downgrade` drops the table and the column, with their data (a day's budget cannot be rebuilt —
it is of its day; keyword days can be re-scraped).

Hand-written, NOT autogenerated.
"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "a6d3f9b2c8e1"
down_revision: Union[str, None] = "e7b2c9d4a6f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_STR = sqlmodel.sql.sqltypes.AutoString


def upgrade() -> None:
    op.create_table(
        "blinkit_ad_campaign_detail_daily",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("platform", _STR(), nullable=False),
        sa.Column("upsert_key", _STR(), nullable=False),
        sa.Column("scrape_job_id", sa.Uuid(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("campaign_type", _STR(), nullable=True),
        sa.Column("target_type", _STR(), nullable=False),
        sa.Column("target", _STR(), nullable=False),
        sa.Column("sub_campaign_id", sa.Integer(), nullable=True),
        sa.Column("match_type", _STR(), nullable=True),
        sa.Column("impressions", sa.Integer(), nullable=False),
        sa.Column("budget_consumed", sa.Float(), nullable=False),
        sa.Column("cpm", sa.Float(), nullable=False),
        sa.Column("direct_atc", sa.Integer(), nullable=False),
        sa.Column("indirect_atc", sa.Integer(), nullable=False),
        sa.Column("direct_sales", sa.Float(), nullable=False),
        sa.Column("indirect_sales", sa.Float(), nullable=False),
        sa.Column("direct_quantities_sold", sa.Integer(), nullable=False),
        sa.Column("indirect_quantities_sold", sa.Integer(), nullable=False),
        sa.Column("new_users_acquired", sa.Integer(), nullable=False),
        sa.Column("most_viewed_position", sa.Integer(), nullable=True),
        sa.Column("direct_roas", sa.Float(), nullable=False),
        sa.Column("total_roas", sa.Float(), nullable=False),
        sa.Column("scraped_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"]),
        sa.ForeignKeyConstraint(["scrape_job_id"], ["scrape_jobs.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("upsert_key"),
    )
    op.create_index("idx_bacdd_tenant_date", "blinkit_ad_campaign_detail_daily",
                    ["tenant_id", "date"])
    op.create_index("idx_bacdd_tenant_campaign_date", "blinkit_ad_campaign_detail_daily",
                    ["tenant_id", "campaign_id", "date"])

    op.add_column("blinkit_ad_campaign_daily",
                  sa.Column("daily_budget", sa.Integer(), nullable=True))


def downgrade() -> None:
    op.drop_column("blinkit_ad_campaign_daily", "daily_budget")
    op.drop_index("idx_bacdd_tenant_campaign_date", table_name="blinkit_ad_campaign_detail_daily")
    op.drop_index("idx_bacdd_tenant_date", table_name="blinkit_ad_campaign_detail_daily")
    op.drop_table("blinkit_ad_campaign_detail_daily")
