"""jobs queue table (runner) — see docs/jobs.md

Adds the `jobs` table: the runner's queue + per-run record. Branches off the DB's
current head (c2d4e6f8a1b3) and does NOT touch the divergent b7c3d8e2f1a9 branch
(search_results / daily_budget) — that reconciliation is separate and coworker-owned.

Hand-written (not autogenerated) so it stays surgical: it creates the `jobs` table
and its indexes and nothing else.

Revision ID: a7f3c2e9d4b1
Revises: c2d4e6f8a1b3
Create Date: 2026-07-15

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a7f3c2e9d4b1'
down_revision: Union[str, Sequence[str], None] = 'c2d4e6f8a1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Reuse the EXISTING jobstatus enum (shared with scrape_jobs / explorer_runs) —
# do not recreate it.
jobstatus = postgresql.ENUM(
    'pending', 'running', 'success', 'failed', name='jobstatus', create_type=False
)
# New enum for the parallel queues.
lane = postgresql.ENUM(
    'batch', 'dashboard', 'live', 'interactive', name='lane', create_type=False
)


def upgrade() -> None:
    lane.create(op.get_bind(), checkfirst=True)

    op.create_table(
        'jobs',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('job_type', sa.String(), nullable=False),
        sa.Column('lane', lane, nullable=False, server_default='batch'),
        sa.Column('tenant_id', sa.Uuid(), nullable=True),
        sa.Column('params', sa.JSON(), nullable=True),
        sa.Column('status', jobstatus, nullable=False, server_default='pending'),
        sa.Column('priority', sa.Integer(), nullable=False, server_default='100'),
        sa.Column('scheduled_for', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column('schedule_id', sa.Integer(), nullable=True),
        sa.Column('attempts', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('max_attempts', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('locked_at', sa.DateTime(), nullable=True),
        sa.Column('locked_by', sa.String(), nullable=True),
        sa.Column('argv', sa.String(), nullable=True),
        sa.Column('exit_code', sa.Integer(), nullable=True),
        sa.Column('log_path', sa.String(), nullable=True),
        sa.Column('peak_rss_mb', sa.Integer(), nullable=True),
        sa.Column('ref_job_id', sa.Uuid(), nullable=True),
        sa.Column('error', sa.String(), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_jobs_lane_claim', 'jobs', ['lane', 'status', 'priority', 'scheduled_for'])
    # `idx_jobs_tenant` is already used by scrape_jobs (index names are schema-global).
    op.create_index('idx_jobs_queue_tenant', 'jobs', ['tenant_id', 'created_at'])
    # Overlap guard: at most one active job per (job_type, tenant_id). Partial, so
    # NULL-tenant (explorer) rows are distinct and never deduped.
    op.create_index(
        'uq_jobs_active', 'jobs', ['job_type', 'tenant_id'], unique=True,
        postgresql_where=sa.text("status IN ('pending', 'running')"),
    )


def downgrade() -> None:
    op.drop_index('uq_jobs_active', table_name='jobs')
    op.drop_index('idx_jobs_queue_tenant', table_name='jobs')
    op.drop_index('idx_jobs_lane_claim', table_name='jobs')
    op.drop_table('jobs')
    lane.drop(op.get_bind(), checkfirst=True)
