"""restructure blinkit marketing tables

Revision ID: adcf3ccd495b
Revises: d5f8a2c1b6e9
Create Date: 2026-06-24 19:21:58.372933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'adcf3ccd495b'
down_revision: Union[str, Sequence[str], None] = 'd5f8a2c1b6e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blinkit_ad_campaign_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upsert_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('campaign_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('budget_consumed', sa.Float(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('atc', sa.Integer(), nullable=False),
    sa.Column('quantities_sold', sa.Integer(), nullable=False),
    sa.Column('ad_sales', sa.Float(), nullable=False),
    sa.Column('roas', sa.Float(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upsert_key')
    )
    op.create_index('idx_bacd_campaign', 'blinkit_ad_campaign_daily', ['tenant_id', 'campaign_id', 'date'], unique=False)
    op.create_index('idx_bacd_tenant_date', 'blinkit_ad_campaign_daily', ['tenant_id', 'date'], unique=False)
    op.create_table('blinkit_ad_campaign_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upsert_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('campaign_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sub_campaign_id', sa.Integer(), nullable=True),
    sa.Column('match_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('budget_consumed', sa.Float(), nullable=False),
    sa.Column('cpm', sa.Float(), nullable=False),
    sa.Column('direct_atc', sa.Integer(), nullable=False),
    sa.Column('indirect_atc', sa.Integer(), nullable=False),
    sa.Column('direct_sales', sa.Float(), nullable=False),
    sa.Column('indirect_sales', sa.Float(), nullable=False),
    sa.Column('direct_quantities_sold', sa.Integer(), nullable=False),
    sa.Column('indirect_quantities_sold', sa.Integer(), nullable=False),
    sa.Column('new_users_acquired', sa.Integer(), nullable=False),
    sa.Column('most_viewed_position', sa.Integer(), nullable=True),
    sa.Column('direct_roas', sa.Float(), nullable=False),
    sa.Column('total_roas', sa.Float(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upsert_key')
    )
    op.create_index('idx_bacdet_tenant_campaign', 'blinkit_ad_campaign_detail', ['tenant_id', 'campaign_id'], unique=False)
    op.create_table('blinkit_ad_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upsert_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_ts', sa.DateTime(), nullable=True),
    sa.Column('end_ts', sa.DateTime(), nullable=True),
    sa.Column('infinite_campaign', sa.Boolean(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upsert_key')
    )
    op.create_index('idx_bac_tenant', 'blinkit_ad_campaigns', ['tenant_id'], unique=False)
    op.create_table('blinkit_brand_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upsert_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('collection_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('number_of_products', sa.Integer(), nullable=False),
    sa.Column('is_dynamic', sa.Boolean(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_on', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upsert_key')
    )
    op.create_table('blinkit_sponsored_sov',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upsert_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monthly_searches', sa.Integer(), nullable=False),
    sa.Column('searches', sa.Integer(), nullable=False),
    sa.Column('sov', sa.Float(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upsert_key')
    )
    op.create_index('idx_bsov_tenant', 'blinkit_sponsored_sov', ['tenant_id', 'date'], unique=False)
    op.create_table('blinkit_visibility_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upsert_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upsert_key')
    )
    op.drop_index(op.f('idx_sov_tenant'), table_name='sponsored_sov')
    op.drop_table('sponsored_sov')
    op.drop_index(op.f('idx_ac_tenant_date'), table_name='ad_campaigns')
    op.drop_table('ad_campaigns')
    op.drop_table('brand_collections')
    op.drop_table('ad_performance_summary')
    op.drop_table('visibility_plans')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visibility_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('upsert_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scrape_job_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scraped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], name=op.f('visibility_plans_scrape_job_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('visibility_plans_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('visibility_plans_pkey')),
    sa.UniqueConstraint('upsert_key', name=op.f('visibility_plans_upsert_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('ad_performance_summary',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('upsert_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scrape_job_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('budget_consumed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('impressions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('budget_distribution', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('scraped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], name=op.f('ad_performance_summary_scrape_job_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('ad_performance_summary_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ad_performance_summary_pkey')),
    sa.UniqueConstraint('upsert_key', name=op.f('ad_performance_summary_upsert_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('brand_collections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('upsert_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scrape_job_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('collection_uuid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('number_of_products', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_dynamic', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_on', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scraped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], name=op.f('brand_collections_scrape_job_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('brand_collections_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('brand_collections_pkey')),
    sa.UniqueConstraint('upsert_key', name=op.f('brand_collections_upsert_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('ad_campaigns',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('upsert_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scrape_job_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_ts', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_ts', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('infinite_campaign', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('budget_consumed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('impressions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('atcs', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('roas', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reach', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scraped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], name=op.f('ad_campaigns_scrape_job_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('ad_campaigns_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ad_campaigns_pkey')),
    sa.UniqueConstraint('upsert_key', name=op.f('ad_campaigns_upsert_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_ac_tenant_date'), 'ad_campaigns', ['tenant_id', 'date'], unique=False)
    op.create_table('sponsored_sov',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('upsert_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scrape_job_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('keyword', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('monthly_searches', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('searches', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sov', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('scraped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], name=op.f('sponsored_sov_scrape_job_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('sponsored_sov_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sponsored_sov_pkey')),
    sa.UniqueConstraint('upsert_key', name=op.f('sponsored_sov_upsert_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_sov_tenant'), 'sponsored_sov', ['tenant_id', 'date'], unique=False)
    op.drop_table('blinkit_visibility_plans')
    op.drop_index('idx_bsov_tenant', table_name='blinkit_sponsored_sov')
    op.drop_table('blinkit_sponsored_sov')
    op.drop_table('blinkit_brand_collections')
    op.drop_index('idx_bac_tenant', table_name='blinkit_ad_campaigns')
    op.drop_table('blinkit_ad_campaigns')
    op.drop_index('idx_bacdet_tenant_campaign', table_name='blinkit_ad_campaign_detail')
    op.drop_table('blinkit_ad_campaign_detail')
    op.drop_index('idx_bacd_tenant_date', table_name='blinkit_ad_campaign_daily')
    op.drop_index('idx_bacd_campaign', table_name='blinkit_ad_campaign_daily')
    op.drop_table('blinkit_ad_campaign_daily')
    # ### end Alembic commands ###
