"""instamart seller sales — per-store daily sales + per-city brand metrics

Revision ID: b1e4c7a9d20f
Revises: a6d2f9c41e87
Create Date: 2026-09-22

The private side of the new Instamart marketplace. Both tables come from the
one Sales xlsx the Brand Portal generates (Reports -> presigned S3 download):

1. **`instamart_seller_store_daily`** — one row per (tenant, date, store, item),
   upserted on `upsert_key`. `store_id` is Instamart's podId, the same id the
   public search scraper stores as `search_listings.merchant_id`, so private
   sales join to public price/stock PER STORE (which neither Zepto nor Blinkit
   allows). `item_code` maps to the public `spin_id` by product_name + variant.

2. **`instamart_brand_city_daily`** — one row per (tenant, date, city): the
   brand-metrics sheet (impressions, orders, GMV, new-to-brand buyers). Every
   metric is nullable — a city can have impressions but no sales. This is NOT a
   store split of table 1; the two are never summed.

No existing table changes and no backfill — the first Instamart sales scrape
after deploy fills them. Additive only: code that predates this never touches
either table. Apply BEFORE deploying code whose models declare them.

`downgrade` drops both tables (rebuildable from one report download).

Hand-written, NOT autogenerated.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

revision: str = 'b1e4c7a9d20f'
down_revision: Union[str, Sequence[str], None] = 'a6d2f9c41e87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'instamart_seller_store_daily',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('upsert_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('area_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('store_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('l1_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('l2_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('l3_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('variant', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('item_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_combo', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('combo_item_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('combo_units_sold', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('base_mrp', sa.Float(), nullable=True),
        sa.Column('units_sold', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('gmv', sa.Float(), nullable=False, server_default='0'),
        sa.Column('scraped_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('upsert_key'),
    )
    op.create_index('idx_issd_tenant_date', 'instamart_seller_store_daily',
                    ['tenant_id', 'date'])
    op.create_index('idx_issd_store', 'instamart_seller_store_daily',
                    ['tenant_id', 'store_id', 'date'])

    op.create_table(
        'instamart_brand_city_daily',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('upsert_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('ntb_buyers', sa.Integer(), nullable=True),
        sa.Column('brand_impressions', sa.Integer(), nullable=True),
        sa.Column('brand_gmv', sa.Float(), nullable=True),
        sa.Column('brand_orders', sa.Integer(), nullable=True),
        sa.Column('scraped_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('upsert_key'),
    )
    op.create_index('idx_ibcd_tenant_date', 'instamart_brand_city_daily',
                    ['tenant_id', 'date'])


def downgrade() -> None:
    op.drop_index('idx_ibcd_tenant_date', table_name='instamart_brand_city_daily')
    op.drop_table('instamart_brand_city_daily')
    op.drop_index('idx_issd_store', table_name='instamart_seller_store_daily')
    op.drop_index('idx_issd_tenant_date', table_name='instamart_seller_store_daily')
    op.drop_table('instamart_seller_store_daily')
