"""zepto: rename the two sales tables to match Blinkit's naming

Revision ID: b6d24a08f3c1
Revises: a3f7c92e51d8
Create Date: 2026-08-30

HAND-WRITTEN, not autogenerated — following the note on c8f4e91a37d2.

────────────────────────────────────────────────────────────────────────────────
WHAT

    zepto_seller_product_perf  ->  zepto_seller_sales
    zepto_seller_sales_daily   ->  zepto_seller_sales_summary

matching `blinkit_seller_sales` and `blinkit_seller_sales_summary`, so the same
idea carries the same name on both platforms. `zepto_seller_product_city_daily`
is deliberately NOT renamed — Blinkit has no counterpart, because its sales
response carries the city inline and needs no second table.

────────────────────────────────────────────────────────────────────────────────
⚠️ THIS IS A BREAKING CHANGE FOR ANY BRANCH THAT HAS NOT PULLED IT

Unlike a dropped orphan table, these two are read by live code. Every branch
points at the same Supabase database, so the moment this applies, code still
saying `zepto_seller_product_perf` fails with:

    UndefinedTableError: relation "zepto_seller_product_perf" does not exist

`dev` contains the Zepto work (b7d3f5a91c04 chains off f4b18e70c2a3), so it
breaks until it merges this. Land the code and the migration together.

────────────────────────────────────────────────────────────────────────────────
16 OBJECTS, NOT 2

Postgres renames a table's dependent objects for nobody. Renaming only the
tables would leave `zepto_seller_sales` carrying `zepto_seller_product_perf_pkey`
— worse than not renaming at all. So this also renames 6 indexes, 2 sequences
and 8 constraints (2 pkey, 2 unique, 4 foreign key).

Note the pkey and unique constraints back indexes of the same name; renaming the
CONSTRAINT renames its index with it, so those are not renamed twice.

────────────────────────────────────────────────────────────────────────────────
DATA

Untouched. `ALTER ... RENAME` is a catalog update — no row is read or rewritten,
no table is copied, and it runs in milliseconds regardless of size. 366 and 44
rows go in, the same 366 and 44 come out.

────────────────────────────────────────────────────────────────────────────────
A CAVEAT ON THE NAME ITSELF

`blinkit_seller_sales` is one row per item per city per day. This table has
`period_start` AND `period_end`, because Zepto's product-performance endpoint
aggregates over whatever window is requested — the schema permits a single row
covering 30 days. In practice the scraper only ever writes single days
(period_start == period_end, and the read services filter on it), but the shared
name implies a guarantee the schema does not make. Anyone writing a new query
against this table should keep the `period_start = period_end` filter that
`zepto_products._conds()` applies.

────────────────────────────────────────────────────────────────────────────────
DOWNGRADE

Fully reversible — every rename is undone in the mirror order. No data is at
risk in either direction.
"""
from alembic import op

revision = "b6d24a08f3c1"
down_revision = "a3f7c92e51d8"
branch_labels = None
depends_on = None

# (old, new) for each object. Order matters only in that the table rename must
# come first — the others are addressed through the (already renamed) table.
_TABLES = [
    ("zepto_seller_product_perf", "zepto_seller_sales"),
    ("zepto_seller_sales_daily", "zepto_seller_sales_summary"),
]

_INDEXES = [
    ("idx_zspp_tenant_period", "idx_zss_tenant_period"),
    ("idx_zssd_tenant_date", "idx_zsss_tenant_date"),
]

_SEQUENCES = [
    ("zepto_seller_product_perf_id_seq", "zepto_seller_sales_id_seq"),
    ("zepto_seller_sales_daily_id_seq", "zepto_seller_sales_summary_id_seq"),
]

# Renaming a constraint renames the index that backs it, so pkey/unique appear
# here and NOT in _INDEXES.
_CONSTRAINTS = [
    # (table_after_rename, old_constraint, new_constraint)
    ("zepto_seller_sales", "zepto_seller_product_perf_pkey", "zepto_seller_sales_pkey"),
    ("zepto_seller_sales", "zepto_seller_product_perf_upsert_key_key", "zepto_seller_sales_upsert_key_key"),
    ("zepto_seller_sales", "zepto_seller_product_perf_tenant_id_fkey", "zepto_seller_sales_tenant_id_fkey"),
    ("zepto_seller_sales", "zepto_seller_product_perf_scrape_job_id_fkey", "zepto_seller_sales_scrape_job_id_fkey"),
    ("zepto_seller_sales_summary", "zepto_seller_sales_daily_pkey", "zepto_seller_sales_summary_pkey"),
    ("zepto_seller_sales_summary", "zepto_seller_sales_daily_upsert_key_key", "zepto_seller_sales_summary_upsert_key_key"),
    ("zepto_seller_sales_summary", "zepto_seller_sales_daily_tenant_id_fkey", "zepto_seller_sales_summary_tenant_id_fkey"),
    ("zepto_seller_sales_summary", "zepto_seller_sales_daily_scrape_job_id_fkey", "zepto_seller_sales_summary_scrape_job_id_fkey"),
]


def upgrade() -> None:
    for old, new in _TABLES:
        op.execute(f'ALTER TABLE "{old}" RENAME TO "{new}"')
    for table, old, new in _CONSTRAINTS:
        op.execute(f'ALTER TABLE "{table}" RENAME CONSTRAINT "{old}" TO "{new}"')
    for old, new in _INDEXES:
        op.execute(f'ALTER INDEX "{old}" RENAME TO "{new}"')
    for old, new in _SEQUENCES:
        op.execute(f'ALTER SEQUENCE "{old}" RENAME TO "{new}"')


def downgrade() -> None:
    for old, new in _SEQUENCES:
        op.execute(f'ALTER SEQUENCE "{new}" RENAME TO "{old}"')
    for old, new in _INDEXES:
        op.execute(f'ALTER INDEX "{new}" RENAME TO "{old}"')
    for table, old, new in _CONSTRAINTS:
        op.execute(f'ALTER TABLE "{table}" RENAME CONSTRAINT "{new}" TO "{old}"')
    for old, new in _TABLES:
        op.execute(f'ALTER TABLE "{new}" RENAME TO "{old}"')
