"""blinkit campaign targeting + per-keyword bid ranges (V7)

Revision ID: b7d3f5a91c04
Revises: f4b18e70c2a3
Create Date: 2026-08-27

Gives the campaign manager the two facts the client asked for, both scraped daily by the
existing Blinkit marketing scrape (docs/campaign-manager.md §7.6b, §7.6c):

  1. **Bid floors.** `blinkit_ad_campaign_keywords` — one row per
     (campaign, keyword, match_type), which is the engine's write key. Blinkit publishes a
     min/max/suggested range per keyword, and it genuinely varies: ₹50 on 'mango', ₹200 on
     'slice', ₹400 on 'cocktail'. Current state, upserted in place — NOT a daily snapshot.
  2. **City targeting + the minimum-budget inputs** — columns on `blinkit_ad_campaigns`.
     `region_ids` are resolved to names at scrape time (`cities` JSON), so nothing
     downstream needs a city directory.

⚠️ `min_cpm` is Blinkit's `min_cpm_config[campaign_type]`. Despite the name it is a BUDGET
input, never a bid floor — the bid floor is the per-keyword `min_bid` in the new table,
which Blinkit publishes directly. There is NO minimum-budget field in any Blinkit response;
its dashboard derives one in the browser. We store the ingredients (`min_cpm`,
`pacing_type`, `billed_amount`, `campaign_cpm`) and let Blinkit reject a too-low budget at
write time rather than reimplementing its formula.

Purely additive: one new table plus six nullable columns. Nothing existing is altered and
no data is backfilled — the next marketing scrape fills everything in.

Hand-written, NOT autogenerated. On this database `--autogenerate` also proposes dropping
ad_automation_rules / ad_automation_actions, loosening two foreign keys' ondelete rules and
dropping idx_listing_tenant_store, none of which are ours (same reason the previous
revision was hand-written).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

revision: str = 'b7d3f5a91c04'
# Chains onto the tip of the Zepto PO line (c8f4e91a37d2 → d7e3b81c4a95 → e2c9a41f78d6 →
# f4b18e70c2a3), which is what the shared DB is actually at. Those four revisions live on
# `feature/zepto-public-scrape` and are NOT yet in dev/main — so this migration cannot be
# DEPLOYED until that branch merges, or the VM will not be able to resolve its ancestor.
down_revision: Union[str, Sequence[str], None] = 'f4b18e70c2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ── Campaign-grain facts from the per-campaign detail call ────────────────
    op.add_column('blinkit_ad_campaigns',
                  sa.Column('region_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blinkit_ad_campaigns',
                  sa.Column('cities', sa.JSON(), nullable=True))
    op.add_column('blinkit_ad_campaigns',
                  sa.Column('min_cpm', sa.Integer(), nullable=True))
    op.add_column('blinkit_ad_campaigns',
                  sa.Column('pacing_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blinkit_ad_campaigns',
                  sa.Column('billed_amount', sa.Float(), nullable=True))
    op.add_column('blinkit_ad_campaigns',
                  sa.Column('campaign_cpm', sa.Integer(), nullable=True))

    # ── Per-keyword bid ranges ────────────────────────────────────────────────
    op.create_table(
        'blinkit_ad_campaign_keywords',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('upsert_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
        sa.Column('campaign_id', sa.Integer(), nullable=False),
        sa.Column('campaign_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('match_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('current_cpm', sa.Integer(), nullable=True),
        sa.Column('min_bid', sa.Integer(), nullable=True),
        sa.Column('max_bid', sa.Integer(), nullable=True),
        sa.Column('suggested_min', sa.Integer(), nullable=True),
        sa.Column('suggested_max', sa.Integer(), nullable=True),
        sa.Column('min_for_boost', sa.Integer(), nullable=True),
        sa.Column('keyword_searches', sa.Integer(), nullable=True),
        sa.Column('scraped_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('upsert_key'),
    )
    op.create_index('idx_backw_tenant_campaign', 'blinkit_ad_campaign_keywords',
                    ['tenant_id', 'campaign_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('idx_backw_tenant_campaign', table_name='blinkit_ad_campaign_keywords')
    op.drop_table('blinkit_ad_campaign_keywords')
    for col in ('campaign_cpm', 'billed_amount', 'pacing_type',
                'min_cpm', 'cities', 'region_type'):
        op.drop_column('blinkit_ad_campaigns', col)
