"""cm settle-once lifecycle — ended_at / settled_at / settle_attempts on bid rules + budget schedules

Revision ID: c1e5a9d3f7b2
Revises: a4e7c2f19b83
Create Date: 2026-09-10

An automation used to have no recorded end. `state` is what a PERSON chose (active / paused
on a bid rule, active / stopped on a budget schedule); nothing recorded that an automation's
last window had closed, so the engines kept acting on ended automations — the end-of-window
reset re-floored them on every fire, and the budget engine wrote their default budget every
hour (Dobra, 2026-09-09).

Three columns on BOTH `cm_bid_rules` and `cm_budget_schedules`:

- `ended_at` TIMESTAMP NULL — when the last window closed. A materialization the reconciler
  maintains for the UI and for SQL. No engine reads it.
- `settled_at` TIMESTAMP NULL — when the automation's final teardown landed (bid back to its
  floor; budget back to its default, campaign stopped if the toggle is on). A latch covers
  an ending only while `settled_at >= that ending's close`.
- `settle_attempts` INTEGER NOT NULL DEFAULT 0 — teardowns that failed for the current
  ending; the settle pass gives up at `CM_SETTLE_MAX_ATTEMPTS`.

**Backfill — `settled_at` = this migration's time (IST wall clock, to the second) on every
existing row, in both tables.** Every ending that has ALREADY happened is treated as done,
so nothing is torn down retroactively. That matters: campaign 637511's automation ended
2026-09-07 and the campaign was restarted by hand on 2026-09-09 — settling it now would
revert its budget and stop it again. An ending AFTER this migration is later than the stamp,
so it is unsettled and covered. No window logic runs in SQL. `ended_at` is left NULL and
`settle_attempts` starts at 0; the next reconcile fills `ended_at` and clears the stamp from
automations that have not ended.

Additive only: nothing is changed or dropped, and existing code keeps working against the
migrated tables (its SELECTs name their columns; its INSERTs get NULL / 0). Apply this
BEFORE deploying code whose models declare the columns — the reverse breaks every query.

`downgrade` drops the three columns and everything in them.

Hand-written, NOT autogenerated.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'c1e5a9d3f7b2'
down_revision: Union[str, Sequence[str], None] = 'a4e7c2f19b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_TABLES = ('cm_bid_rules', 'cm_budget_schedules')


def upgrade() -> None:
    for table in _TABLES:
        op.add_column(table, sa.Column('ended_at', sa.DateTime(), nullable=True))
        op.add_column(table, sa.Column('settled_at', sa.DateTime(), nullable=True))
        op.add_column(table, sa.Column('settle_attempts', sa.Integer(), nullable=False,
                                       server_default='0'))
        # Naive IST wall clock, like every timestamp in this app (app/utils/time.now_ist).
        op.execute(f"UPDATE {table} "
                   f"SET settled_at = date_trunc('second', now() AT TIME ZONE 'Asia/Kolkata')")


def downgrade() -> None:
    for table in _TABLES:
        op.drop_column(table, 'settle_attempts')
        op.drop_column(table, 'settled_at')
        op.drop_column(table, 'ended_at')
