"""canonical cities + per-source aliases, and city_id on stores (V7.3)

Revision ID: c1e8a4d20f7b
Revises: b7d3f5a91c04
Create Date: 2026-08-27

The same place is spelled differently on every surface we read. Measured 2026-08-27:

    Gurugram              Blinkit ads
    Gurgaon               Blinkit SELLER dashboard   ← same company, different name
    hr-ncr                our store catalog
    delhi ncr             Zepto's store catalog      ← a bucket, not a city
    BLR - Bengaluru       Zepto's sales report

Five vocabularies, so translating source→source needs a rule per PAIR and grows with every
new surface. One canonical registry needs one alias per name.

    cities         the canonical list. Our ids and slugs; names seeded from a marketplace's
                   city directory because it is a free, curated list of Indian q-commerce
                   cities. Nothing is locked to it — a display name can be corrected later
                   without touching an alias, since aliases point at the id.
    city_aliases   every raw string from every source, keyed `<marketplace>:<surface>`
                   because the mismatch is per surface, not per marketplace.

`marketplace_locations.city_id` is the piece that makes the grouped names stop mattering:
each store resolves its OWN city from its pincode (present on 3287/3288 active stores), so
`hr-ncr`'s 77 stores individually become Gurugram and Zepto's `delhi ncr` blob splits
correctly. The existing `city` text column is UNTOUCHED — the config workbook writes it and
the public scrapers and reports group by it; this is additive alongside.

Purely additive: two new tables, one nullable column. Nothing existing is altered and no
data is backfilled here — `cli sync` populates city_id.

Hand-written, NOT autogenerated (see the note on b7d3f5a91c04).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

revision: str = 'c1e8a4d20f7b'
down_revision: Union[str, Sequence[str], None] = 'b7d3f5a91c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'cities',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('pincode_prefixes', sa.JSON(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug'),
    )
    op.create_index('idx_cities_slug', 'cities', ['slug'], unique=False)

    op.create_table(
        'city_aliases',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('city_id', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('source', 'alias', name='uq_city_alias_source_alias'),
    )
    op.create_index('idx_city_alias_city', 'city_aliases', ['city_id'], unique=False)

    op.add_column('marketplace_locations', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_mploc_city', 'marketplace_locations', 'cities',
                          ['city_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('fk_mploc_city', 'marketplace_locations', type_='foreignkey')
    op.drop_column('marketplace_locations', 'city_id')
    op.drop_index('idx_city_alias_city', table_name='city_aliases')
    op.drop_table('city_aliases')
    op.drop_index('idx_cities_slug', table_name='cities')
    op.drop_table('cities')
