"""zepto: per-campaign keyword performance per day (P38)

Revision ID: c3a9e5d7f2b1
Revises: b8e2d4f6a1c3
Create Date: 2026-10-06

ONE new table, nothing else changes:

**`zepto_ad_campaign_detail`** — one row per (tenant, campaign, keyword, match type,
day): spend, revenue, impressions, clicks, orders, add-to-carts, ctr / cpc / cpm,
roas / robas, and the direct (`same_skus`) / halo (`other_skus`) order counts.

Why: Zepto keyword metrics were stored only at BRAND grain (`zepto_ad_keyword_daily`
has no campaign id), so the keyword-automation wizard could show no performance per
campaign. Zepto's campaign detail page reports keywords per campaign per day — probed
read-only 2026-10-06 on campaign 2443333; a campaign-day's rows equal our stored campaign
row on every figure. Named after Blinkit's `blinkit_ad_campaign_detail`.

Filled by the daily Zepto ads scrape (the campaigns that had impressions on each day of
its window); a 30-day backfill is a separate, later step. Nothing reads it until the
code that uses it is deployed.

Additive only: code that predates this never touches the table. Apply BEFORE deploying
code whose models declare it.

`downgrade` drops the table and everything in it (rebuildable by re-scraping).

Index names are `idx_zacdet_*`: Postgres index names are database-wide, and the first
attempt (`idx_zacd_*`, 2026-10-06) collided with `zepto_ad_campaign_daily`'s
`idx_zacd_tenant_date` and rolled back cleanly — nothing was left behind.

Hand-written, NOT autogenerated.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

revision: str = 'c3a9e5d7f2b1'
down_revision: Union[str, Sequence[str], None] = 'b8e2d4f6a1c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_STR = sqlmodel.sql.sqltypes.AutoString


def upgrade() -> None:
    op.create_table(
        'zepto_ad_campaign_detail',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('platform', _STR(), nullable=False),
        sa.Column('upsert_key', _STR(), nullable=False),
        sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('brand_id', _STR(), nullable=False),
        sa.Column('campaign_id', sa.Integer(), nullable=False),
        sa.Column('campaign_category', _STR(), nullable=False),
        sa.Column('keyword', _STR(), nullable=False),
        sa.Column('match_type', _STR(), nullable=True),
        sa.Column('spend', sa.Float(), nullable=False),
        sa.Column('revenue', sa.Float(), nullable=True),
        sa.Column('impressions', sa.Integer(), nullable=False),
        sa.Column('clicks', sa.Integer(), nullable=False),
        sa.Column('orders', sa.Integer(), nullable=True),
        sa.Column('atc', sa.Integer(), nullable=True),
        sa.Column('ctr', sa.Float(), nullable=True),
        sa.Column('cpc', sa.Float(), nullable=True),
        sa.Column('cpm', sa.Float(), nullable=True),
        sa.Column('roas', sa.Float(), nullable=True),
        sa.Column('robas', sa.Float(), nullable=True),
        sa.Column('same_skus', sa.Integer(), nullable=True),
        sa.Column('other_skus', sa.Integer(), nullable=True),
        sa.Column('scraped_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('upsert_key'),
    )
    op.create_index('idx_zacdet_tenant_date', 'zepto_ad_campaign_detail',
                    ['tenant_id', 'date'])
    op.create_index('idx_zacdet_tenant_campaign_date', 'zepto_ad_campaign_detail',
                    ['tenant_id', 'campaign_id', 'date'])


def downgrade() -> None:
    op.drop_index('idx_zacdet_tenant_campaign_date', table_name='zepto_ad_campaign_detail')
    op.drop_index('idx_zacdet_tenant_date', table_name='zepto_ad_campaign_detail')
    op.drop_table('zepto_ad_campaign_detail')
