"""one LIVE bid rule per (tenant, platform, campaign, keyword, match type) — ZC-C9

Revision ID: c4f7b2e81a93
Revises: a9757fea742a
Create Date: 2026-09-23

Nothing stopped two bid automations chasing the SAME keyword on the same campaign. They do
not merge: each reads the live bid, decides against its own target and ceiling, and writes —
so the bid oscillates every tick, costs real money, and neither rule's History explains why
it keeps moving. Both marketplaces are affected; on Zepto it is worse, because every bid
write is a whole-campaign PUT.

A PARTIAL unique index, on `active` rows only. Pausing a rule sets `active = false`
(`repo.set_bid_state`), which deliberately frees the keyword — someone may replace a paused
rule without deleting it, and the rule's history is worth keeping. Resuming re-checks
(`repo.require_no_live_bid_rule`), so the freed slot cannot be taken twice.

Indexed on `lower(trim(keyword))` and `upper(coalesce(match_type,'EXACT'))`: "Pink Toffee"
and "pink toffee" are one keyword to the marketplace, and a NULL match type IS EXACT
everywhere in the engines.

Verified before writing this: 2 bid rules exist in the shared DB (both Blinkit) and 0
duplicate groups, so the index can be created without cleaning anything up first. Re-check
with the query in the checklist (ZC-C9) before applying — a duplicate created meanwhile
would make CREATE INDEX fail, which is the safe outcome, not a broken deploy.

Re-parented 2026-09-28 at the release merge of `dev`: written on top of `a6d2f9c41e87`, but
the Instamart chain (`b1e4c7a9d20f` … `a9757fea742a`) landed on the shared DB first, from
the same parent. Pointing `down_revision` at the end of that chain keeps ONE head; it was
not applied anywhere before the move, so nothing records the old parent. Until it is
applied, `repo.require_no_live_bid_rule` enforces the same rule in code.

`downgrade` drops the index; no data is touched either way.

Hand-written, NOT autogenerated.
"""
from typing import Sequence, Union

from alembic import op

revision: str = 'c4f7b2e81a93'
down_revision: Union[str, Sequence[str], None] = 'a9757fea742a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_INDEX = "uq_cm_bid_rule_live"


def upgrade() -> None:
    op.execute(
        f"CREATE UNIQUE INDEX IF NOT EXISTS {_INDEX} ON cm_bid_rules "
        "(tenant_id, platform, campaign_id, lower(trim(keyword)), "
        "upper(coalesce(match_type, 'EXACT'))) WHERE active"
    )


def downgrade() -> None:
    op.execute(f"DROP INDEX IF EXISTS {_INDEX}")
