"""zepto: nullable advertiser_id + account_ref; marketplace-scoped active-job guard

Revision ID: c8f4e91a37d2
Revises: a91d47e0b3c2
Create Date: 2026-08-27

Two changes, batched because both are prerequisites for running a second
marketplace and neither is worth its own index rebuild.

HAND-WRITTEN, not autogenerated. `--autogenerate` on this project sweeps in
unrelated drift (it has previously proposed dropping `ad_automation_*` and
`idx_listing_tenant_store`, and churning FKs). Everything below is only the
intended change.

────────────────────────────────────────────────────────────────────────────────
1. `cm_platform_accounts`: advertiser_id NULLABLE, + account_ref

   The table exists per (tenant, platform) and also carries `live_armed`, so a
   Zepto row is needed even though Zepto has no integer advertiser id to store.

   Blinkit MUST store one: the advertiser id appears in no read API, so it is
   captured from a dashboard write and sent explicitly (B3). Zepto returns its
   `brand_id` in the login response — so instead of storing a value to send, we
   store one to CHECK: `adapter.set_advertiser` refuses the write unless the live
   session's brand ids contain `account_ref`.

2. `uq_jobs_active`: include the marketplace

   Today: UNIQUE (job_type, tenant_id) WHERE status IN ('pending','running').

   That guard is right WITHIN a marketplace — two concurrent Blinkit budget runs
   for one tenant are a real hazard — but wrong ACROSS them. A tenant running both
   marketplaces cannot have a Zepto and a Blinkit `cm.budget_scheduler` active at
   once; the second is rejected as `DuplicateActiveJob`. The failure is quiet and
   misleading: the second marketplace's run simply never happens, and the message
   says "already active" as though it were a genuine overlap.

   `marketplace` lives in `jobs.params` (a `json` column), hence an expression
   index. Verified before writing this: `json_object_field_text` is IMMUTABLE, so
   the expression is indexable, and all 5,530 existing rows already COALESCE to
   'blinkit'.

   ⚠️ The COALESCE is load-bearing. A bare `params->>'marketplace'` is NULL for
   every pre-existing job, and NULLs are DISTINCT in a unique index — which would
   silently disable the overlap guard for exactly the jobs that have relied on it.

SAFETY
   Purely additive and relaxing:
     * a NOT NULL -> NULL relaxation cannot fail on existing data;
     * a new nullable column needs no backfill;
     * ADDING a column to a unique index only ever permits MORE rows, so no
       existing data can violate the new index.
   Safe to apply ahead of the deploy: running code does not name the new column,
   and the new index accepts everything the old one did. The dangerous ordering is
   the reverse — code before migration — which is what broke every `cm` operation
   when the arming feature shipped first.
"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

revision = "c8f4e91a37d2"
down_revision = "a91d47e0b3c2"
branch_labels = None
depends_on = None

# Mirrors the predicate already on the index, enum casts included.
_ACTIVE = "status = ANY (ARRAY['pending'::jobstatus, 'running'::jobstatus])"
_MP = "COALESCE(params->>'marketplace', 'blinkit')"


def upgrade() -> None:
    op.alter_column(
        "cm_platform_accounts", "advertiser_id",
        existing_type=sa.Integer(), nullable=True,
    )
    op.add_column(
        "cm_platform_accounts",
        sa.Column("account_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )

    op.drop_index("uq_jobs_active", table_name="jobs")
    op.execute(
        f"CREATE UNIQUE INDEX uq_jobs_active ON jobs "
        f"(job_type, tenant_id, {_MP}) WHERE {_ACTIVE}"
    )


def downgrade() -> None:
    op.drop_index("uq_jobs_active", table_name="jobs")
    op.execute(
        f"CREATE UNIQUE INDEX uq_jobs_active ON jobs "
        f"(job_type, tenant_id) WHERE {_ACTIVE}"
    )

    op.drop_column("cm_platform_accounts", "account_ref")
    # ⚠️ Re-imposing NOT NULL fails if any row has a null advertiser_id — i.e. if a
    # Zepto account was configured after the upgrade. That is correct: silently
    # inventing a value to satisfy the constraint would be worse. Delete or fill
    # those rows first if you genuinely need to roll back.
    op.alter_column(
        "cm_platform_accounts", "advertiser_id",
        existing_type=sa.Integer(), nullable=False,
    )
