"""marketplace_locations: drop zone, add location_name + address

The dark-store catalog moves to the Blinkit darkstore export as source of truth: one
row per **express** store, with its real address and precise coordinate.

`zone` is dropped — it was never populated (0 of 2216 rows carried a value) and the
store's sub-city name is what it was always meant to hold. That is now `location_name`
("Shahganj"), with `address` carrying the full street address for display. Both come
straight from the export.

Written by hand rather than autogenerated: the campaign-manager branch
(`b7c3d8e2f1a9`) is a second, unapplied head whose drift autogenerate would sweep into
this migration. This revision deliberately chains off `b8e5d1a3f9c2` only.

See docs/darkstores.md.

Revision ID: d4a9c7e2b6f1
Revises: b8e5d1a3f9c2
Create Date: 2026-07-17

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = "d4a9c7e2b6f1"
down_revision: Union[str, Sequence[str], None] = "b8e5d1a3f9c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default so the existing rows satisfy NOT NULL; `cli sync` fills them in.
    op.add_column(
        "marketplace_locations",
        sa.Column("location_name", sqlmodel.sql.sqltypes.AutoString(),
                  nullable=False, server_default=""),
    )
    op.add_column(
        "marketplace_locations",
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(),
                  nullable=False, server_default=""),
    )
    op.drop_column("marketplace_locations", "zone")


def downgrade() -> None:
    op.add_column(
        "marketplace_locations",
        sa.Column("zone", sqlmodel.sql.sqltypes.AutoString(),
                  nullable=False, server_default=""),
    )
    op.drop_column("marketplace_locations", "address")
    op.drop_column("marketplace_locations", "location_name")
