"""cm city stores — freeze the dark store a city's bid automations measure at

Revision ID: d7c3e9a1f5b2
Revises: c1e5a9d3f7b2
Create Date: 2026-09-11

A bid rule names a city, and the store it measured at inside that city was the city's lowest
`merchant_id` — deterministic, but a store nobody chose — copied onto the rule as lat/lon at
save time. Changing it meant editing every rule.

1. **`cm_city_stores`** — one frozen store per (platform, city, rank). `tenant_id` NULL is the
   GLOBAL default (set from the CLI); a `tenant_id` row is one client's override. Keyed by
   `merchant_id` rather than a FK to `marketplace_locations.id`, because `cli sync --prune`
   deletes and re-creates catalog rows. Two PARTIAL unique indexes, one per layer: a plain
   UNIQUE would let rows with a NULL tenant repeat. `rank` 1 is the store; higher ranks are
   reserved for multi-store measurement, which is not built.

2. **`cm_bid_rules.city_id`** NULL → cities.id. Set = the rule follows its city's frozen
   store, resolved on every bid run; NULL = pinned to its own lat/lon.

**Backfill:** each existing rule's `city_id` from the catalog store at its EXACT saved
coordinates, only where those coordinates belong to exactly one registered city. Checked
2026-09-11 against the 4 rules on the shared DB: all 4 match one store each. No
`cm_city_stores` rows are created, and a city with nothing frozen keeps every rule at its
saved store — so nothing measures anywhere new until someone sets a store.

Additive only. Apply BEFORE deploying code whose models declare these — the reverse breaks
every query on `cm_bid_rules`.

`downgrade` drops the table, the column, and everything in them.

Hand-written, NOT autogenerated.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

revision: str = 'd7c3e9a1f5b2'
down_revision: Union[str, Sequence[str], None] = 'c1e5a9d3f7b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'cm_city_stores',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=True),
        sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('city_id', sa.Integer(), nullable=False),
        sa.Column('merchant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('rank', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['city_id'], ['cities.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('uq_cm_city_store_global', 'cm_city_stores',
                    ['platform', 'city_id', 'rank'], unique=True,
                    postgresql_where=sa.text('tenant_id IS NULL'))
    op.create_index('uq_cm_city_store_tenant', 'cm_city_stores',
                    ['tenant_id', 'platform', 'city_id', 'rank'], unique=True,
                    postgresql_where=sa.text('tenant_id IS NOT NULL'))

    op.add_column('cm_bid_rules', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_cm_bid_rules_city', 'cm_bid_rules', 'cities',
                          ['city_id'], ['id'])
    op.execute("""
        UPDATE cm_bid_rules r
        SET city_id = m.city_id
        FROM (
            SELECT mp_slug, lat, lon, min(city_id) AS city_id
            FROM marketplace_locations
            WHERE city_id IS NOT NULL AND lat IS NOT NULL AND lon IS NOT NULL
            GROUP BY mp_slug, lat, lon
            HAVING count(DISTINCT city_id) = 1
        ) m
        WHERE r.city_id IS NULL
          AND m.mp_slug = r.platform AND m.lat = r.lat AND m.lon = r.lon
    """)


def downgrade() -> None:
    op.drop_constraint('fk_cm_bid_rules_city', 'cm_bid_rules', type_='foreignkey')
    op.drop_column('cm_bid_rules', 'city_id')
    op.drop_index('uq_cm_city_store_tenant', table_name='cm_city_stores')
    op.drop_index('uq_cm_city_store_global', table_name='cm_city_stores')
    op.drop_table('cm_city_stores')
