"""zepto: seller product performance split by city

Revision ID: d7e3b81c4a95
Revises: c8f4e91a37d2
Create Date: 2026-08-26

HAND-WRITTEN, not autogenerated — following the note on c8f4e91a37d2:
`--autogenerate` on this project sweeps in unrelated drift (it has previously
proposed dropping `ad_automation_*` and churning FKs). Only the intended change
is below.

────────────────────────────────────────────────────────────────────────────────
WHAT AND WHY

One new table: `zepto_seller_product_city_daily`, one row per tenant x SKU x
city x day.

It exists because the Analytics "Revenue by category & city" heatmap needs city
and category on the SAME row, and no existing Zepto table has both:

    zepto_seller_sales_city_daily   city x day    -- no category
    zepto_seller_product_perf       SKU x day     -- no city

Zepto's product-performance response carries no city dimension, but its
`cityIds` parameter does filter by one (verified 2026-08-26: Bengaluru returned
9 SKUs / Rs 52,215 for 25-Aug while three other cities returned nothing). So the
split is scraped one call per city, the same shape as `fetch_sales_by_city`.

WHY A NEW TABLE RATHER THAN city_id/city_name COLUMNS ON THE EXISTING ONE

`zepto_seller_product_perf` is SKU x day summed over every city. Adding city
columns would leave old rows meaning "all cities" and new rows meaning "one
city" in one table, so `sum(gmv)` would be right or double-counted depending on
which rows a query happened to catch. `zepto_ad_breakdown_daily` already
demonstrates that failure mode: it totals ~3x its real spend because it stacks
three views of the same money behind a `dimension` column.

Different grain -> different table. The two hold the same rupees at different
resolutions and must never be summed together; the model docstring says so.

SAFETY

Purely additive: one CREATE TABLE and its indexes. No existing table, column,
index or row is touched, so nothing running can be affected and there is no
backfill. The table is empty until `cli scrape zepto-sales` next runs.
"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

revision = "d7e3b81c4a95"
down_revision = "c8f4e91a37d2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "zepto_seller_product_city_daily",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("platform", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("upsert_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scrape_job_id", sa.Uuid(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("city_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("city_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("product_variant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("product_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sku_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("category_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("subcategory_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("gmv", sa.Float(), nullable=False),
        sa.Column("qty_sold", sa.Integer(), nullable=False),
        sa.Column("scraped_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["scrape_job_id"], ["scrape_jobs.id"]),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"]),
        sa.PrimaryKeyConstraint("id"),
        # The upsert target. city_id is part of the parser's key, so re-running a
        # day re-writes each city's rows in place instead of appending.
        sa.UniqueConstraint("upsert_key"),
    )
    op.create_index(
        "idx_zspcd_tenant_date",
        "zepto_seller_product_city_daily",
        ["tenant_id", "date"],
    )
    op.create_index(
        "idx_zspcd_city",
        "zepto_seller_product_city_daily",
        ["tenant_id", "city_id", "date"],
    )


def downgrade() -> None:
    op.drop_index("idx_zspcd_city", table_name="zepto_seller_product_city_daily")
    op.drop_index("idx_zspcd_tenant_date", table_name="zepto_seller_product_city_daily")
    op.drop_table("zepto_seller_product_city_daily")
