"""zepto: PO management — purchase orders, goods receipts, shipping notices

Revision ID: e2c9a41f78d6
Revises: d7e3b81c4a95
Create Date: 2026-08-27

HAND-WRITTEN, not autogenerated — following the note on c8f4e91a37d2:
`--autogenerate` on this project sweeps in unrelated drift (it has previously
proposed dropping `ad_automation_*` and churning FKs). Only the intended change
is below.

────────────────────────────────────────────────────────────────────────────────
WHAT AND WHY

Three new tables from Zepto's `/vendor` PO app (brands.zepto.co.in/vendor/po/*),
whose APIs live on the SAME host as the analytics endpoints and accept the SAME
saved session — recon 2026-08-27, no browser and no WAF challenge needed.

    zepto_po    what Zepto ordered      (header only, see below)
    zepto_grn   what Zepto received     po_qty vs grn_qty
    zepto_asn   what the vendor shipped po_qty -> asn_qty -> grn_qty

The point of this is FILL RATE. `grn_qty / po_qty` is the same quantity Blinkit's
seller scorecard reports, and Zepto publishes no scorecard page at all — so this
is the only route to the Overview "Fill rate (MoM)" tile for a Zepto client.
Observed on the recon: 201 received against 202 ordered = 99.5%.

WHY THREE TABLES

A PO, its shipment and its receipt are three grains, and each can exist without
the others — a PO with no ASN yet, a GRN against a PO issued before the scrape
window. One merged table would need nullable everything and make `sum(qty)`
meaningless. Same rule the four `zepto_ad_*` tables follow.

WHAT THIS DOES NOT COVER

PO **line items**. `/api/v1/po/filter` returns `itemsCount` but not the lines;
those sit behind a per-PO detail call that has not been captured. So this backs
Overview's PO value and Fill rate, but NOT the per-SKU "PO History" tab that
Blinkit's `blinkit_po_items` backs. That needs one more recon pass, and the line
table is also where cost price and margin live.

KEYING

`upsert_key` is the PO/GRN/ASN id alone — NOT id+date. A PO is a durable object
whose status and received quantity change over its life, so re-scraping an
overlapping window must UPDATE it in place rather than create a second row. That
is deliberately the opposite of the sales tables, where each day is its own fact.

SAFETY

Purely additive: three CREATE TABLEs and their indexes. No existing table,
column, index or row is touched, so nothing running can be affected and there is
no backfill. All three are empty until `cli scrape zepto-po` runs.
"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

revision = "e2c9a41f78d6"
down_revision = "d7e3b81c4a95"
branch_labels = None
depends_on = None

_STR = sqlmodel.sql.sqltypes.AutoString


def _common() -> list:
    """Bookkeeping columns every Zepto table carries, in the same order."""
    return [
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("platform", _STR(), nullable=False),
        sa.Column("upsert_key", _STR(), nullable=False),
        sa.Column("scrape_job_id", sa.Uuid(), nullable=True),
    ]


def _constraints() -> list:
    return [
        sa.ForeignKeyConstraint(["scrape_job_id"], ["scrape_jobs.id"]),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("upsert_key"),
    ]


def upgrade() -> None:
    op.create_table(
        "zepto_po",
        *_common(),
        sa.Column("po_id", _STR(), nullable=False),
        sa.Column("vin_po_no", _STR(), nullable=True),
        sa.Column("status", _STR(), nullable=True),
        sa.Column("vendor_code", _STR(), nullable=True),
        sa.Column("vendor", _STR(), nullable=True),
        sa.Column("vendor_relation_type", _STR(), nullable=True),
        sa.Column("location_code", _STR(), nullable=True),
        sa.Column("location", _STR(), nullable=True),
        sa.Column("mh_code", _STR(), nullable=True),
        sa.Column("city", _STR(), nullable=True),
        sa.Column("po_date", sa.Date(), nullable=True),
        sa.Column("scheduled_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("items_count", sa.Integer(), nullable=True),
        sa.Column("total_qty", sa.Integer(), nullable=True),
        sa.Column("total_asn_qty", sa.Integer(), nullable=True),
        sa.Column("total_grn_qty", sa.Integer(), nullable=True),
        sa.Column("total_value", sa.Float(), nullable=True),
        sa.Column("payment_terms", _STR(), nullable=True),
        sa.Column("source", _STR(), nullable=True),
        sa.Column("entity_code", _STR(), nullable=True),
        sa.Column("scraped_at", sa.DateTime(), nullable=False),
        *_constraints(),
    )
    op.create_index("idx_zpo_tenant_date", "zepto_po", ["tenant_id", "po_date"])
    op.create_index("idx_zpo_status", "zepto_po", ["tenant_id", "status"])

    op.create_table(
        "zepto_grn",
        *_common(),
        sa.Column("grn_no", _STR(), nullable=False),
        sa.Column("asn_no", _STR(), nullable=True),
        sa.Column("ext_asn_no", _STR(), nullable=True),
        sa.Column("po_id", _STR(), nullable=True),
        sa.Column("vin_po_no", _STR(), nullable=True),
        sa.Column("status", _STR(), nullable=True),
        sa.Column("vendor_code", _STR(), nullable=True),
        sa.Column("vendor_name", _STR(), nullable=True),
        sa.Column("location_code", _STR(), nullable=True),
        sa.Column("location", _STR(), nullable=True),
        sa.Column("po_qty", sa.Integer(), nullable=True),
        sa.Column("asn_qty", sa.Integer(), nullable=True),
        sa.Column("grn_qty", sa.Integer(), nullable=True),
        sa.Column("remaining_qty", sa.Integer(), nullable=True),
        sa.Column("po_value", sa.Float(), nullable=True),
        sa.Column("grn_value", sa.Float(), nullable=True),
        sa.Column("grn_date", sa.Date(), nullable=True),
        sa.Column("entity_code", _STR(), nullable=True),
        sa.Column("scraped_at", sa.DateTime(), nullable=False),
        *_constraints(),
    )
    op.create_index("idx_zgrn_tenant_date", "zepto_grn", ["tenant_id", "grn_date"])
    op.create_index("idx_zgrn_po", "zepto_grn", ["tenant_id", "po_id"])

    op.create_table(
        "zepto_asn",
        *_common(),
        sa.Column("asn_no", _STR(), nullable=False),
        sa.Column("ext_asn_no", _STR(), nullable=True),
        sa.Column("po_id", _STR(), nullable=True),
        sa.Column("vin_po_no", _STR(), nullable=True),
        sa.Column("status", _STR(), nullable=True),
        sa.Column("vendor_code", _STR(), nullable=True),
        sa.Column("vendor_name", _STR(), nullable=True),
        sa.Column("location_code", _STR(), nullable=True),
        sa.Column("external_location_code", _STR(), nullable=True),
        sa.Column("location", _STR(), nullable=True),
        sa.Column("po_qty", sa.Integer(), nullable=True),
        sa.Column("asn_qty", sa.Integer(), nullable=True),
        sa.Column("grn_qty", sa.Integer(), nullable=True),
        sa.Column("remaining_qty", sa.Integer(), nullable=True),
        sa.Column("po_value", sa.Float(), nullable=True),
        sa.Column("asn_value", sa.Float(), nullable=True),
        sa.Column("asn_date", sa.Date(), nullable=True),
        sa.Column("entity_code", _STR(), nullable=True),
        sa.Column("scraped_at", sa.DateTime(), nullable=False),
        *_constraints(),
    )
    op.create_index("idx_zasn_tenant_date", "zepto_asn", ["tenant_id", "asn_date"])
    op.create_index("idx_zasn_po", "zepto_asn", ["tenant_id", "po_id"])


def downgrade() -> None:
    op.drop_index("idx_zasn_po", table_name="zepto_asn")
    op.drop_index("idx_zasn_tenant_date", table_name="zepto_asn")
    op.drop_table("zepto_asn")

    op.drop_index("idx_zgrn_po", table_name="zepto_grn")
    op.drop_index("idx_zgrn_tenant_date", table_name="zepto_grn")
    op.drop_table("zepto_grn")

    op.drop_index("idx_zpo_status", table_name="zepto_po")
    op.drop_index("idx_zpo_tenant_date", table_name="zepto_po")
    op.drop_table("zepto_po")
