"""normalize blinkit PO tables (header, items, snapshot)

Revision ID: e428162c451f
Revises: c4e7a1b9f2d3
Create Date: 2026-06-22 02:20:31.100072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e428162c451f'
down_revision: Union[str, Sequence[str], None] = 'c4e7a1b9f2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blinkit_po_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upsert_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('po_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('line_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uom_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('variant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('units_ordered', sa.Integer(), nullable=True),
    sa.Column('remaining_quantity', sa.Integer(), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('landing_rate', sa.Float(), nullable=True),
    sa.Column('mrp', sa.Float(), nullable=True),
    sa.Column('margin_percentage', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('tax_value', sa.Float(), nullable=True),
    sa.Column('cgst_value', sa.Float(), nullable=True),
    sa.Column('sgst_value', sa.Float(), nullable=True),
    sa.Column('igst_value', sa.Float(), nullable=True),
    sa.Column('cess_value', sa.Float(), nullable=True),
    sa.Column('bucket_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upsert_key')
    )
    op.create_index('idx_po_items_tenant_po', 'blinkit_po_items', ['tenant_id', 'po_number'], unique=False)
    op.add_column('blinkit_po_snapshots', sa.Column('total_raised', sa.Integer(), nullable=True))
    op.add_column('blinkit_po_snapshots', sa.Column('scheduled', sa.Integer(), nullable=True))
    op.add_column('blinkit_po_snapshots', sa.Column('created', sa.Integer(), nullable=True))
    op.add_column('blinkit_po_snapshots', sa.Column('cancelled', sa.Integer(), nullable=True))
    op.add_column('blinkit_po_snapshots', sa.Column('expired_unfulfilled', sa.Integer(), nullable=True))
    op.add_column('blinkit_po_snapshots', sa.Column('expired_partial', sa.Integer(), nullable=True))
    op.add_column('blinkit_po_snapshots', sa.Column('po_amount', sa.Float(), nullable=True))
    op.add_column('blinkit_po_snapshots', sa.Column('items_delivered', sa.Integer(), nullable=True))
    op.drop_column('blinkit_po_snapshots', 'raw')
    op.add_column('blinkit_pos', sa.Column('po_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('vendor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('vendor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('manufacturer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('manufacturer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('facility_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('facility_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('city_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('outlet_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('po_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('issue_date', sa.DateTime(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('expiry_date', sa.DateTime(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('delivery_date', sa.DateTime(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('schedule_date', sa.DateTime(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('scheduled_on', sa.DateTime(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('total_units_ordered', sa.Integer(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('item_count', sa.Integer(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('total_grn_quantity', sa.Integer(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('total_po_amount', sa.Float(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('multiple_grn', sa.Integer(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('load_size', sa.Integer(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('download_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('po_excel_report_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('grn_report_excel_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('pm_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('pm_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('pm_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('entity_vendor_cin', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('entity_vendor_legal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('delivery_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blinkit_pos', sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('blinkit_pos', 'raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blinkit_pos', sa.Column('raw', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('blinkit_pos', 'updated_by')
    op.drop_column('blinkit_pos', 'created_by')
    op.drop_column('blinkit_pos', 'updated_at')
    op.drop_column('blinkit_pos', 'created_at')
    op.drop_column('blinkit_pos', 'delivery_type')
    op.drop_column('blinkit_pos', 'entity_vendor_legal_name')
    op.drop_column('blinkit_pos', 'entity_vendor_cin')
    op.drop_column('blinkit_pos', 'pm_email')
    op.drop_column('blinkit_pos', 'pm_phone')
    op.drop_column('blinkit_pos', 'pm_name')
    op.drop_column('blinkit_pos', 'grn_report_excel_url')
    op.drop_column('blinkit_pos', 'po_excel_report_url')
    op.drop_column('blinkit_pos', 'download_url')
    op.drop_column('blinkit_pos', 'active')
    op.drop_column('blinkit_pos', 'load_size')
    op.drop_column('blinkit_pos', 'multiple_grn')
    op.drop_column('blinkit_pos', 'total_po_amount')
    op.drop_column('blinkit_pos', 'total_grn_quantity')
    op.drop_column('blinkit_pos', 'item_count')
    op.drop_column('blinkit_pos', 'total_units_ordered')
    op.drop_column('blinkit_pos', 'scheduled_on')
    op.drop_column('blinkit_pos', 'schedule_date')
    op.drop_column('blinkit_pos', 'delivery_date')
    op.drop_column('blinkit_pos', 'expiry_date')
    op.drop_column('blinkit_pos', 'issue_date')
    op.drop_column('blinkit_pos', 'address')
    op.drop_column('blinkit_pos', 'po_type_id')
    op.drop_column('blinkit_pos', 'outlet_id')
    op.drop_column('blinkit_pos', 'city_name')
    op.drop_column('blinkit_pos', 'facility_name')
    op.drop_column('blinkit_pos', 'facility_id')
    op.drop_column('blinkit_pos', 'manufacturer_name')
    op.drop_column('blinkit_pos', 'manufacturer_id')
    op.drop_column('blinkit_pos', 'vendor_name')
    op.drop_column('blinkit_pos', 'vendor_id')
    op.drop_column('blinkit_pos', 'po_state')
    op.add_column('blinkit_po_snapshots', sa.Column('raw', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('blinkit_po_snapshots', 'items_delivered')
    op.drop_column('blinkit_po_snapshots', 'po_amount')
    op.drop_column('blinkit_po_snapshots', 'expired_partial')
    op.drop_column('blinkit_po_snapshots', 'expired_unfulfilled')
    op.drop_column('blinkit_po_snapshots', 'cancelled')
    op.drop_column('blinkit_po_snapshots', 'created')
    op.drop_column('blinkit_po_snapshots', 'scheduled')
    op.drop_column('blinkit_po_snapshots', 'total_raised')
    op.drop_index('idx_po_items_tenant_po', table_name='blinkit_po_items')
    op.drop_table('blinkit_po_items')
    # ### end Alembic commands ###
