"""drop the retired v1 campaign-manager tables

Revision ID: e7a3c85f2b19
Revises: 6eb277c7b1fb
Create Date: 2026-09-03

Phase B of the v1 retirement. The v1 engine (`ad_campaigns/`, the `cli ads` group, the
three `ads.*` job types, its half of `ads_service`, the `/ads/budget-schedules` +
`/ads/bid-optimizer` API and the v1 UI) was deleted from the codebase on 2026-09-03. These
are the tables it owned. Nothing reads or writes them any more — verified by grep for the
models and by the FK audit below.

Dropped (row counts at 2026-09-03):

  budget_schedules          6      v1 budget rules — superseded by cm_budget_schedules
  budget_schedule_rules     6      windows on the above
  budget_scheduler_log      7085   v1 run history — superseded by cm_run_log
  bid_optimizer_rules       0      v1 bid rules — superseded by cm_bid_rules
  bid_optimizer_log         165    v1 bid history — superseded by cm_run_log
  campaign_data_cache       48     keyword/product cache; its last reader (the v2 bid
                                   form, via /ads/campaigns/{id}/keywords) was repointed
                                   at blinkit_ad_campaign_keywords on 2026-09-03, and the
                                   job that filled it last ran 2026-07-29
  ad_automation_rules       3      ⚠️ NOT v1 — an older abandoned experiment (revision
  ad_automation_actions     90     9cba1aca0fa7, perf-triggered automation). Never had a
                                   model or a line of code referencing it. Dropped here
                                   because it is the same class of dead weight; this
                                   reverses the earlier "deprecate, don't delete" call.

⚠️ Order matters — children before parents:
  ad_automation_actions → ad_automation_rules   (rule_id FK)
  budget_schedule_rules → budget_schedules      (schedule_id FK)
Everything else is a leaf: their only FKs point OUT at `tenants`/`users`, and the FK audit
confirmed nothing outside points IN. In particular **`jobs` does not reference any of
these** — its only link to v1 is the `lane` enum VALUE, which is untouched here.

⚠️ The `lane` enum keeps `budget_scheduler` / `bid_optimizer` / `sync_campaign_data`.
~3,700 historical `jobs` rows still carry those values, `lane` is a str-Enum column, and
Postgres has no `ALTER TYPE ... DROP VALUE` at all — removing one means recreating the type
and rewriting the column. Dead enum values cost nothing. Leave them.

Hand-written, NOT autogenerated — `--autogenerate` on this database has a history of
proposing collateral drops (see revision aef972735d57's note).

**The data is not recoverable after this.** It was reviewed and deemed stale before the
drop; the one finding worth keeping out of `bid_optimizer_log` (that campaign 568887 lost
its Delhi-NCR targeting to the v1 optimizer on 2026-07-13) is recorded in
docs/campaign-manager.md §8.2b. `downgrade()` restores the SCHEMA only, never the rows.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

revision: str = 'e7a3c85f2b19'
down_revision: Union[str, Sequence[str], None] = '6eb277c7b1fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Drop the v1 tables. Children first — see the FK note in the docstring."""
    for table in (
        "ad_automation_actions",      # FK → ad_automation_rules
        "ad_automation_rules",
        "budget_schedule_rules",      # FK → budget_schedules
        "budget_schedules",
        "budget_scheduler_log",
        "bid_optimizer_rules",
        "bid_optimizer_log",
        "campaign_data_cache",
    ):
        # Indexes go with the table; dropping them separately would fail on re-run.
        op.drop_table(table)


def downgrade() -> None:
    """Recreate the SCHEMA only. The rows are gone for good — this is a structural undo,
    not a restore, and a v1 engine to use them no longer exists in the codebase."""
    op.create_table(
        "budget_schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("campaign_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("default_budget", sa.Float(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "campaign_id",
                            name="uq_budget_schedule_tenant_campaign"),
    )
    op.create_index("idx_bs_tenant", "budget_schedules", ["tenant_id"])

    op.create_table(
        "budget_schedule_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("days", sa.JSON(), nullable=True),
        sa.Column("time_slots", sa.JSON(), nullable=True),
        sa.Column("start_time", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("end_time", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("start_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("end_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("date", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("budget", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["schedule_id"], ["budget_schedules.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_bsr_schedule", "budget_schedule_rules", ["schedule_id"])

    op.create_table(
        "budget_scheduler_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=True),
        sa.Column("campaign_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("budget_applied", sa.Float(), nullable=False),
        sa.Column("rule", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_bsl_tenant", "budget_scheduler_log", ["tenant_id", "timestamp"])

    op.create_table(
        "bid_optimizer_rules",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("campaign_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("keyword", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("match_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_position", sa.Integer(), nullable=False),
        sa.Column("min_bid", sa.Integer(), nullable=False),
        sa.Column("max_bid", sa.Integer(), nullable=False),
        sa.Column("start_time", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("stop_time", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("start_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("stop_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("location_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("brand_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_cpm", sa.Integer(), nullable=True),
        sa.Column("last_position", sa.Float(), nullable=True),
        sa.Column("last_bid_updated_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_bor_tenant", "bid_optimizer_rules", ["tenant_id"])

    op.create_table(
        "bid_optimizer_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=True),
        sa.Column("campaign_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("keyword", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("old_cpm", sa.Integer(), nullable=True),
        sa.Column("new_cpm", sa.Integer(), nullable=True),
        sa.Column("position", sa.Float(), nullable=True),
        sa.Column("target_position", sa.Integer(), nullable=True),
        sa.Column("impressions", sa.Integer(), nullable=True),
        sa.Column("detail", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_bol_tenant", "bid_optimizer_log", ["tenant_id", "timestamp"])

    op.create_table(
        "campaign_data_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("keywords", sa.JSON(), nullable=True),
        sa.Column("products", sa.JSON(), nullable=True),
        sa.Column("synced_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "campaign_id", name="uq_cdc_tenant_campaign"),
    )
    op.create_index("idx_cdc_tenant", "campaign_data_cache", ["tenant_id"])

    op.create_table(
        "ad_automation_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("scope_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False,
                  server_default="all"),
        sa.Column("scope_value", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("metric", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("operator", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("window_days", sa.Integer(), nullable=False, server_default="7"),
        sa.Column("action_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("action_value", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_aar_tenant", "ad_automation_rules", ["tenant_id"])

    op.create_table(
        "ad_automation_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("campaign_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("metric", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("metric_value", sa.Float(), nullable=False),
        sa.Column("operator", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("action_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("action_value", sa.Float(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False,
                  server_default="pending"),
        sa.Column("reasoning", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("detected_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("resolved_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"]),
        sa.ForeignKeyConstraint(["rule_id"], ["ad_automation_rules.id"]),
        sa.ForeignKeyConstraint(["resolved_by"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
