"""zepto: stock + growth as of the scrape, per product per day (P41, step 1)

Revision ID: e7b2c9d4a6f3
Revises: f1a8c3e5b7d2
Create Date: 2026-10-07

ONE new table, nothing else changes:

**`zepto_soh`** — one row per (tenant, product, scrape day): stock on hand and Zepto's
week-on-week / month-on-month growth, as Zepto reported them WHEN WE ASKED. Named after
Blinkit's `blinkit_soh`.

Why: those three figures sit on `zepto_seller_sales`, keyed on the SALES day — but Zepto
returns the same value for every day a run asks about, and they move run to run (P8,
2026-10-07: Brik Oven Sour Cream, sales days 09-29..10-06 all held stock 102 from the 10-07
run). Keyed on the sales day, the product page's stock trend is one flat line for the last 8
days and lagged ~8 days before that.

Step 1 of 3, so nothing on the shared database breaks:
  1. (this) add the table; the scrape writes it AND keeps writing the old columns.
  2. readers (`app/services/zepto_products.py`) switch to it, once it holds some days.
  3. drop the three columns from `zepto_seller_sales` — only after every running copy of
     the code (VM `main`, UAT, laptops) is past step 1. Old code writes those columns, so
     dropping them earlier would make its sales save fail.

Additive only: code that predates this never touches the table. Apply BEFORE deploying code
whose models declare it — that code writes the table on every sales scrape, and would fail
the sales save without it.

Chained after the merge `f1a8c3e5b7d2`, which rejoins this branch's line (`c3a9e5d7f2b1`)
with dev's `d4b7e2a9c615` (Sayantani, 2026-10-07: drops a dead Instamart ads column).
Index name `idx_zsoh_tenant_date` and the table name were checked free in `pg_class` on
2026-10-07 (index names are database-wide).

`downgrade` drops the table and everything in it (no history can be rebuilt: a reading is of
its moment — but the old columns still hold the latest values until step 3).

Hand-written, NOT autogenerated.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

revision: str = 'e7b2c9d4a6f3'
down_revision: Union[str, Sequence[str], None] = 'f1a8c3e5b7d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_STR = sqlmodel.sql.sqltypes.AutoString


def upgrade() -> None:
    op.create_table(
        'zepto_soh',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('platform', _STR(), nullable=False),
        sa.Column('upsert_key', _STR(), nullable=False),
        sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('product_variant_id', _STR(), nullable=False),
        sa.Column('sku_name', _STR(), nullable=True),
        sa.Column('stock_on_hand', sa.Integer(), nullable=True),
        sa.Column('week_on_week_growth', sa.Float(), nullable=True),
        sa.Column('month_on_month_growth', sa.Float(), nullable=True),
        sa.Column('scraped_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('upsert_key'),
    )
    op.create_index('idx_zsoh_tenant_date', 'zepto_soh', ['tenant_id', 'date'])


def downgrade() -> None:
    op.drop_index('idx_zsoh_tenant_date', table_name='zepto_soh')
    op.drop_table('zepto_soh')
