"""cm store stock + per-store bid readings — multi-store bidding with stock awareness

Revision ID: f3c8a1d6b9e2
Revises: d7c3e9a1f5b2
Create Date: 2026-09-17

A keyword automation now measures at up to three frozen stores per city (`cm_city_stores`
ranks 1-3, no schema change there) and bids for its target at EVERY store where the campaign
is listed and in stock. Two new tables support that:

1. **`cm_store_stock`** — the stock cache. One row per (tenant, platform, store): our brand's
   products found by one brand search at that store, with availability (`products` JSON), and
   whether the read reached the end of our brand (`complete`). Replaced on each successful
   read, roughly hourly; a failed read writes nothing, so a missing or stale row means "stock
   unknown", which never stops a raise.

2. **`cm_bid_store_reads`** — append-only, one row per store per automation per bid tick: what
   each store showed (verdict, position, eligibility), the bid in force, and whether it was the
   store that bound the decision. Trimmed to 30 days as it is written.

No existing table changes and no backfill. Additive only: code that predates this never touches
either table. Apply BEFORE deploying code whose models declare them.

`downgrade` drops both tables and everything in them.

Hand-written, NOT autogenerated.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

revision: str = 'f3c8a1d6b9e2'
down_revision: Union[str, Sequence[str], None] = 'd7c3e9a1f5b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'cm_store_stock',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('merchant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('served_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False,
                  server_default=''),
        sa.Column('complete', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('products', sa.JSON(), nullable=True),
        sa.Column('checked_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'platform', 'merchant_id', name='uq_cm_store_stock'),
    )

    op.create_table(
        'cm_bid_store_reads',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('rule_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('campaign_id', sa.Integer(), nullable=False),
        sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('city_id', sa.Integer(), nullable=True),
        sa.Column('merchant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False,
                  server_default=''),
        sa.Column('store_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False,
                  server_default=''),
        sa.Column('rank', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('bid', sa.Integer(), nullable=True),
        sa.Column('eligibility', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('verdict', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('position', sa.Float(), nullable=True),
        sa.Column('binding', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('dry_run', sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column('observed_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_cm_store_reads_tenant', 'cm_bid_store_reads',
                    ['tenant_id', 'observed_at'])
    op.create_index('idx_cm_store_reads_rule', 'cm_bid_store_reads',
                    ['rule_id', 'observed_at'])


def downgrade() -> None:
    op.drop_index('idx_cm_store_reads_rule', table_name='cm_bid_store_reads')
    op.drop_index('idx_cm_store_reads_tenant', table_name='cm_bid_store_reads')
    op.drop_table('cm_bid_store_reads')
    op.drop_table('cm_store_stock')
