"""zepto: PO line items — per-SKU order lines, cost price and margin

Revision ID: f4b18e70c2a3
Revises: e2c9a41f78d6
Create Date: 2026-08-27

HAND-WRITTEN, not autogenerated — following the note on c8f4e91a37d2.

────────────────────────────────────────────────────────────────────────────────
WHAT AND WHY

One table: `zepto_po_items`, one row per SKU per purchase order, from
`GET /api/v1/po/{po_id}/items` (one call per PO — the filter endpoint reports
`itemsCount` but not the lines).

Two things live here and NOWHERE else in the system:

1. **Cost price.** `unit_price` is what Zepto pays; `mrp` is what it sells at.
   Observed 22-Aug-2026: Rosemary & Cheddar at Rs 53.33 against an Rs 80 MRP.
   No other Zepto endpoint reports a cost.

2. **Per-SKU fill rate.** `grn_qty / po_qty` per product. The GRN table gives
   fill rate per delivery; this gives it per SKU — which is how we found that
   two products were halved while two others in the SAME delivery were accepted
   in full (GrnCode56384162: Whole Wheat 152->73 and Rosemary 50->25, while
   Artisinal 70->70 and Pretzel Bagel 12->12). That rules out truck timing,
   temperature and dock capacity, which would hit every line equally.

THE JOIN THAT MAKES IT USEFUL

`product_variant_id` is Zepto's `pvId` — the SAME id `zepto_seller_product_perf`
keys on. So PO lines attach to the Products page directly, with no name matching
and no `sku_map` bridge. That is unlike Blinkit, where private and public ids
share no key at all.

KEYING

`(po_id, product_variant_id)` rather than Zepto's line uuid. The uuid appears
stable, but the pair is what actually identifies a line, and keying on it means a
re-scrape updates quantities in place as stock arrives against an open PO.

SAFETY

Purely additive: one CREATE TABLE and two indexes. No existing table, column,
index or row is touched. Empty until `cli scrape zepto-po` next runs.
"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

revision = "f4b18e70c2a3"
down_revision = "e2c9a41f78d6"
branch_labels = None
depends_on = None

_STR = sqlmodel.sql.sqltypes.AutoString


def upgrade() -> None:
    op.create_table(
        "zepto_po_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("platform", _STR(), nullable=False),
        sa.Column("upsert_key", _STR(), nullable=False),
        sa.Column("scrape_job_id", sa.Uuid(), nullable=True),
        sa.Column("po_id", _STR(), nullable=False),
        sa.Column("line_id", _STR(), nullable=True),
        sa.Column("status", _STR(), nullable=True),
        sa.Column("sku_code", _STR(), nullable=True),
        sa.Column("sku_name", _STR(), nullable=True),
        sa.Column("product_variant_id", _STR(), nullable=True),
        sa.Column("ean_no", _STR(), nullable=True),
        sa.Column("hsn_code", _STR(), nullable=True),
        sa.Column("brand", _STR(), nullable=True),
        sa.Column("po_qty", sa.Integer(), nullable=True),
        sa.Column("asn_qty", sa.Integer(), nullable=True),
        sa.Column("grn_qty", sa.Integer(), nullable=True),
        sa.Column("remaining_qty", sa.Integer(), nullable=True),
        sa.Column("unit_price", sa.Float(), nullable=True),
        sa.Column("mrp", sa.Float(), nullable=True),
        sa.Column("total_value", sa.Float(), nullable=True),
        sa.Column("cgst", sa.Float(), nullable=True),
        sa.Column("sgst", sa.Float(), nullable=True),
        sa.Column("igst", sa.Float(), nullable=True),
        sa.Column("cess", sa.Float(), nullable=True),
        sa.Column("scheduled_date", sa.Date(), nullable=True),
        sa.Column("scraped_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["scrape_job_id"], ["scrape_jobs.id"]),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("upsert_key"),
    )
    op.create_index("idx_zpoi_tenant_po", "zepto_po_items", ["tenant_id", "po_id"])
    op.create_index(
        "idx_zpoi_pv", "zepto_po_items", ["tenant_id", "product_variant_id"]
    )


def downgrade() -> None:
    op.drop_index("idx_zpoi_pv", table_name="zepto_po_items")
    op.drop_index("idx_zpoi_tenant_po", table_name="zepto_po_items")
    op.drop_table("zepto_po_items")
