"""cm_run_log: record every tick's decision, not just the changes

Revision ID: f4c81b3d7e26
Revises: e7a3c85f2b19
Create Date: 2026-09-04

The bid engine narrates every decision it makes — but only the ones that CHANGED something
were persisted. "Held at ₹201 because the position is already at target" existed solely in
Cloud Logging, which is not joinable to our data, has its own retention, and cannot be shown
in the product. A per-campaign / per-automation view needs the ticks where nothing happened
just as much as the ones where something did: "why did my bid not move for six hours" is the
question users actually ask.

Three columns, all nullable and all additive:

  rule_id   which automation this decision belongs to. Deliberately NOT a foreign key —
            history must survive the deletion of the rule it describes, and `cm_run_log`
            also carries budget/activation rows whose "rule" lives in a different table.
  position  the observed search position. THE input to every bid decision, and until now it
            existed only as prose inside `reason`.
  target    the effective target the decision was made against, which differs from the
            rule's own whenever a target has been relaxed.

Without `position` and `target` a per-automation view can show THAT a decision happened but
not why, which is the entire point of showing it.

Also adds an index on (tenant_id, campaign_id, timestamp): every tick now writes a row, so
the per-campaign query needs to stop scanning the whole tenant's history.

⚠️ Volume. At ~15-minute ticks an in-window keyword writes ~4 rows/hour where it previously
wrote ~0. The table is 641 rows / 264 kB today, so this is comfortably absorbed, but it is
now a table that grows with TIME rather than with ACTIVITY and will need a retention policy
(the model has said "retention policy later" since it was created — this is what makes it
real). Not added here: dropping history is a decision, not a migration detail.

Hand-written, NOT autogenerated.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'f4c81b3d7e26'
down_revision: Union[str, Sequence[str], None] = 'e7a3c85f2b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('cm_run_log', sa.Column('rule_id', sa.Integer(), nullable=True))
    op.add_column('cm_run_log', sa.Column('position', sa.Float(), nullable=True))
    op.add_column('cm_run_log', sa.Column('target', sa.Integer(), nullable=True))
    op.create_index('idx_cm_runlog_campaign', 'cm_run_log',
                    ['tenant_id', 'campaign_id', 'timestamp'], unique=False)


def downgrade() -> None:
    op.drop_index('idx_cm_runlog_campaign', table_name='cm_run_log')
    for col in ('target', 'position', 'rule_id'):
        op.drop_column('cm_run_log', col)
